'use strict';

const vscode = require('vscode');
const fs = require('fs');
const os = require('os');
const path = require('path');

const CSS_FILE = path.join(os.homedir(), '.vscode', 'varun-architectus.css');

const DEFAULTS = {
  ryzeEnabled: true,
  ryzeText: 'IUDEX',
  ryzeBackText: 'RYZE',
  ryzeOpacity: 100,
  ryzeGlitchEnabled: true,
  ryzeGlitchIntensity: 100,
  ryzeGlitchFrequency: 2,
  ryzeTypingGlitch: true,
  ryzeSpeed: 10,
  ryzeSize: 14,
  ryzePerspective: 900,
  ryzeGlowColor: '#00d4b1',
  ryzeExtrudeColor: '#101116',
  ryzeGlowIntensity: 50,
  colorStrings: '#0059ff',
  colorTypes: '#029790',
  colorKeywords: '#94058a',
  colorNumbers: '#1a1b03',
  colorFunctions: '#d0f30c',
  colorVariables: '#004cf1',
  colorErrors: '#940303',
  colorComments: '#00d4b1',
  cursorColor1: '#00d4b1',
  cursorColor2: '#007fd4',
  cursorPulseSpeed: 5,
  syntaxGlowEnabled: true,
  scanlinesEnabled: true,
  scanlinesOpacity: 20,
  scrollbarColor: '#bd93f9',
  scrollbarHoverColor: '#ff79c6',
};

function getWorkbenchHtml() {
  return path.join(vscode.env.appRoot, 'out', 'vs', 'workbench', 'workbench.desktop.main.html');
}

function cssFileUrl() {
  return 'file://' + CSS_FILE.split(path.sep).join('/');
}

function isInjected() {
  try { return fs.readFileSync(getWorkbenchHtml(), 'utf8').includes('architectus-inject'); }
  catch { return false; }
}

const TYPING_SCRIPT = '<script>(function(){' +
  'var t;' +
  'document.addEventListener(\'keydown\',function(e){' +
  'if(e.key.length>1&&e.key!==\'Backspace\'&&e.key!==\'Delete\')return;' +
  'document.body.classList.add(\'architectus-typing\');' +
  'clearTimeout(t);' +
  't=setTimeout(function(){document.body.classList.remove(\'architectus-typing\');},220);' +
  '});' +
  '})();<\/script>';

function injectCSS() {
  const htmlPath = getWorkbenchHtml();
  let html = fs.readFileSync(htmlPath, 'utf8');
  if (html.includes('architectus-inject')) return;
  const tag = '<!-- architectus-inject -->' +
    '<link rel="stylesheet" data-name="architectus" href="' + cssFileUrl() + '">' +
    TYPING_SCRIPT;
  fs.writeFileSync(htmlPath, html.replace('</head>', tag + '\n</head>'), 'utf8');
}

function uninjectCSS() {
  const htmlPath = getWorkbenchHtml();
  let html = fs.readFileSync(htmlPath, 'utf8');
  html = html.replace(/<!-- architectus-inject -->[\s\S]*?<\/script>\n?/g, '');
  fs.writeFileSync(htmlPath, html, 'utf8');
}

function showPermissionError() {
  const cmd = 'sudo chown -R $(whoami) "' + vscode.env.appRoot + '"';
  vscode.window.showErrorMessage('Architectus: Permission denied. Fix ownership first.', 'Copy Command')
    .then(c => { if (c === 'Copy Command') vscode.env.clipboard.writeText(cmd); });
}

function hexToRgba(hex, alpha) {
  const r = parseInt(hex.slice(1, 3), 16);
  const g = parseInt(hex.slice(3, 5), 16);
  const b = parseInt(hex.slice(5, 7), 16);
  return 'rgba(' + r + ', ' + g + ', ' + b + ', ' + alpha.toFixed(3) + ')';
}

function generateCSS(s) {
  const sc    = (s.scanlinesOpacity / 100).toFixed(3);
  const gi    = s.ryzeGlowIntensity / 100;
  const pulse = (s.cursorPulseSpeed / 10).toFixed(1);
  const op    = ((s.ryzeOpacity || 100) / 100).toFixed(2);
  const front = (s.ryzeText    || 'IUDEX').replace(/\\/g,'\\\\').replace(/"/g,'\\"');
  const back  = (s.ryzeBackText|| 'RYZE' ).replace(/\\/g,'\\\\').replace(/"/g,'\\"');
  const glitch = s.ryzeGlitchEnabled && (s.ryzeGlitchIntensity || 0) > 0;
  const gx    = (s.ryzeGlitchIntensity || 40) / 100;
  const gs    = Math.max(2, Math.round(gx * 8)); // shake / CA offset px
  const cBlur = Math.max(2, Math.round(gx * 6)); // chromatic aberration blur px

  let c = '/* Varun\'s Architectus — generated by Architectus Directives */\n\n';

  c += '/* --- Syntax glow --- */\n';
  if (s.syntaxGlowEnabled !== false) {
    c += '.mtk1  { text-shadow: 0 0 6px rgba(255,255,255,0.6); }\n';
    c += '.mtk3  { text-shadow: 0 0 8px ' + s.colorStrings + ', 0 0 16px ' + s.colorStrings + '; }\n';
    c += '.mtk4  { text-shadow: 0 0 8px ' + s.colorTypes + ', 0 0 16px ' + s.colorTypes + '; }\n';
    c += '.mtk5  { text-shadow: 0 0 8px ' + s.colorKeywords + ', 0 0 14px ' + s.colorKeywords + '; }\n';
    c += '.mtk6  { text-shadow: 0 0 8px ' + s.colorNumbers + ', 0 0 14px ' + s.colorNumbers + '; }\n';
    c += '.mtk7  { text-shadow: 0 0 8px ' + s.colorFunctions + ', 0 0 14px ' + s.colorFunctions + '; }\n';
    c += '.mtk8  { text-shadow: 0 0 6px ' + s.colorVariables + ', 0 0 12px ' + s.colorVariables + '; }\n';
    c += '.mtk9  { text-shadow: 0 0 8px ' + s.colorErrors + ', 0 0 14px ' + s.colorErrors + '; }\n';
    c += '.mtk12 { text-shadow: 0 0 6px ' + s.colorComments + '; }\n';
  } else {
    c += '.mtk1,.mtk3,.mtk4,.mtk5,.mtk6,.mtk7,.mtk8,.mtk9,.mtk12 { text-shadow: none; }\n';
  }
  c += '\n';

  c += '/* --- Cursor --- */\n';
  c += '.cursor { box-shadow: 0 0 6px 2px ' + s.cursorColor1 + ', 0 0 14px 4px ' + s.cursorColor2 + '; animation: cursor-pulse ' + pulse + 's ease-in-out infinite; }\n';
  c += '@keyframes cursor-pulse {\n';
  c += '  0%,100% { box-shadow: 0 0 6px 2px ' + s.cursorColor1 + ', 0 0 14px 4px ' + s.cursorColor2 + '; }\n';
  c += '  50%      { box-shadow: 0 0 12px 4px ' + s.cursorColor1 + ', 0 0 28px 8px ' + s.cursorColor2 + '; }\n}\n\n';

  c += '/* --- Scanlines on editor-container (frees ::after for back-face text) --- */\n';
  c += '.editor-container { position: relative; }\n';
  if (s.scanlinesEnabled) {
    c += '.editor-container::after {\n';
    c += '  content: ""; position: absolute; top: 0; left: 0; right: 0; bottom: 0;\n';
    c += '  background: repeating-linear-gradient(to bottom, transparent 0px, transparent 3px, rgba(0,0,0,' + sc + ') 3px, rgba(0,0,0,' + sc + ') 4px);\n';
    c += '  pointer-events: none; z-index: 100;\n}\n\n';
  }

  // Background glitch
  const bgA1 = hexToRgba(s.ryzeGlowColor, 0.07 * gx);
  const bgA2 = hexToRgba(s.ryzeExtrudeColor, 0.05 * gx);
  if (glitch) {
    c += '/* --- Background glitch --- */\n';
    c += '.editor-container::before {\n';
    c += '  content: ""; position: absolute; top: 0; left: 0; right: 0; bottom: 0;\n';
    c += '  pointer-events: none; z-index: 5; opacity: 0;\n';
    c += '  animation: bg-glitch 11s steps(1) infinite;\n}\n';
    c += '@keyframes bg-glitch {\n';
    c += '  0%, 84%, 92%, 100% { opacity: 0; background: none; }\n';
    c += '  84.5% { opacity: 1; background: linear-gradient(to bottom, transparent 22%, ' + bgA1 + ' 22%, ' + bgA1 + ' 23%, transparent 23%, transparent 58%, ' + bgA2 + ' 58%, ' + bgA2 + ' 59%, transparent 59%); }\n';
    c += '  85.5% { opacity: 0; background: none; }\n';
    c += '  87%   { opacity: 1; background: linear-gradient(to bottom, transparent 71%, ' + bgA1 + ' 71%, ' + bgA1 + ' 73%, transparent 73%); }\n';
    c += '  88%   { opacity: 0; background: none; }\n';
    c += '  90%   { opacity: 1; background: linear-gradient(to bottom, transparent 41%, ' + bgA2 + ' 41%, ' + bgA2 + ' 42%, transparent 42%); }\n';
    c += '  91%   { opacity: 0; background: none; }\n}\n\n';
  }

  c += '/* --- Editor chrome --- */\n';
  c += '.editor-container .monaco-editor { position: relative; }\n';
  c += '.monaco-editor .current-line { box-shadow: inset 0 0 30px ' + hexToRgba(s.ryzeGlowColor, 0.08) + '; border-color: ' + hexToRgba(s.ryzeGlowColor, 0.25) + ' !important; }\n';
  c += '.monaco-scrollable-element > .scrollbar > .slider { background: ' + hexToRgba(s.scrollbarColor, 0.4) + ' !important; border-radius: 4px; box-shadow: 0 0 6px ' + s.scrollbarColor + '; }\n';
  c += '.monaco-scrollable-element > .scrollbar > .slider:hover { background: ' + hexToRgba(s.scrollbarHoverColor, 0.6) + ' !important; box-shadow: 0 0 10px ' + s.scrollbarHoverColor + '; }\n';
  c += '.tab.active { box-shadow: inset 0 -2px 0 ' + s.cursorColor1 + ', 0 0 10px ' + hexToRgba(s.cursorColor1, 0.3) + '; }\n';
  c += '.monaco-list-row.focused { box-shadow: inset 2px 0 0 ' + s.ryzeGlowColor + '; }\n';
  c += '.xterm-cursor-layer .xterm-cursor { box-shadow: 0 0 6px 2px ' + s.colorKeywords + '; }\n';
  c += '.minimap { opacity: 0.6; filter: saturate(1.5) brightness(0.9); }\n\n';

  if (s.ryzeEnabled) {
    const shadow =
      '    1px 1px 0 ' + hexToRgba(s.ryzeExtrudeColor, 0.40) + ',\n' +
      '    2px 2px 0 ' + hexToRgba(s.ryzeExtrudeColor, 0.35) + ',\n' +
      '    3px 3px 0 ' + hexToRgba(s.ryzeExtrudeColor, 0.30) + ',\n' +
      '    4px 4px 0 ' + hexToRgba(s.ryzeExtrudeColor, 0.25) + ',\n' +
      '    5px 5px 0 ' + hexToRgba(s.ryzeExtrudeColor, 0.18) + ',\n' +
      '    6px 6px 0 ' + hexToRgba(s.ryzeExtrudeColor, 0.12) + ',\n' +
      '    7px 7px 0 ' + hexToRgba(s.ryzeGlowColor, 0.08) + ',\n' +
      '    8px 8px 0 ' + hexToRgba(s.ryzeGlowColor, 0.05) + ',\n' +
      '    0 0 40px  ' + hexToRgba(s.ryzeGlowColor, gi) + ',\n' +
      '    0 0 80px  ' + hexToRgba(s.ryzeGlowColor, gi * 0.55) + ',\n' +
      '    0 0 120px ' + hexToRgba(s.ryzeExtrudeColor, gi * 0.33);

    const shared =
      '  position: absolute; top: 50%; left: 50%;\n' +
      '  font-size: clamp(48px,' + s.ryzeSize + 'vw,420px);\n' +
      '  font-weight: 900; font-family: \'Arial Black\',\'Impact\',sans-serif;\n' +
      '  letter-spacing: 0.12em; white-space: nowrap; color: transparent;\n' +
      '  -webkit-text-stroke: 1.5px ' + hexToRgba(s.ryzeGlowColor, 0.35) + ';\n' +
      '  text-shadow:\n' + shadow + ';\n' +
      '  pointer-events: none; z-index: 10; mix-blend-mode: screen; opacity: ' + op + ';\n' +
      '  backface-visibility: hidden; -webkit-backface-visibility: hidden;\n';

    const freq   = s.ryzeGlitchFrequency || 7;
    const freqB  = Math.round(freq * 13 / 9);
    const typing = s.ryzeTypingGlitch;
    const glitchAnimA = glitch ? ', text-glitch-a var(--architectus-freq-a) steps(1) infinite' : '';
    const glitchAnimB = glitch ? ', text-glitch-b var(--architectus-freq-b) steps(1) infinite' : '';
    const typingAnim  = (glitch && typing) ? ', text-glitch-typing 0.22s steps(3) 1' : '';

    c += ':root { --architectus-speed: ' + s.ryzeSpeed + 's;';
    if (glitch) c += ' --architectus-freq-a: ' + freq + 's; --architectus-freq-b: ' + freqB + 's;';
    c += ' }\n';

    c += '/* --- Front/back text flip --- */\n';
    c += '.editor-container .monaco-editor::before,\n.editor-container .monaco-editor::after {\n' + shared + '}\n';
    c += '.editor-container .monaco-editor::before {\n';
    c += '  content: "' + front + '";\n';
    c += '  animation: architectus-front var(--architectus-speed) linear infinite' + glitchAnimA + ';\n}\n';
    c += '.editor-container .monaco-editor::after {\n';
    c += '  content: "' + back + '";\n';
    c += '  animation: architectus-back var(--architectus-speed) linear infinite' + glitchAnimB + ';\n}\n';

    c += '@keyframes architectus-front {\n';
    c += '  from { transform: translate(-50%,-50%) rotateY(0deg); }\n';
    c += '  to   { transform: translate(-50%,-50%) rotateY(360deg); }\n}\n';
    c += '@keyframes architectus-back {\n';
    c += '  from { transform: translate(-50%,-50%) rotateY(180deg); }\n';
    c += '  to   { transform: translate(-50%,-50%) rotateY(540deg); }\n}\n';

    if (glitch) {
      const s0 = '0 0';
      // Chromatic aberration: split extrude color left, glow color right (like the
      // shader's per-segment R/G/B channel offset). Direction alternates per frame.
      // Each jolt frame is immediately followed by a center frame → jolt → center → jolt.
      const ca1 = hexToRgba(s.ryzeExtrudeColor, 0.90);
      const ca2 = hexToRgba(s.ryzeGlowColor,    0.90);
      const ca1d = hexToRgba(s.ryzeExtrudeColor, 0.70);
      const ca2d = hexToRgba(s.ryzeGlowColor,    0.70);
      const b = cBlur;
      const dsLR  = 'drop-shadow(-' + gs + 'px 0 ' + b + 'px ' + ca1 + ') drop-shadow(' + gs + 'px 0 ' + b + 'px ' + ca2 + ')';
      const dsRL  = 'drop-shadow(' + gs + 'px 0 ' + b + 'px ' + ca1 + ') drop-shadow(-' + gs + 'px 0 ' + b + 'px ' + ca2 + ')';
      const dsLRd = 'drop-shadow(-' + Math.round(gs*0.6) + 'px 0 ' + (b+1) + 'px ' + ca1d + ') drop-shadow(' + Math.round(gs*0.6) + 'px 0 ' + (b+1) + 'px ' + ca2d + ')';

      c += '@keyframes text-glitch-a {\n';
      c += '  0%, 84%, 86%, 88%, 90%, 92%, 94%, 100% { filter: none; translate: ' + s0 + '; opacity: ' + op + '; }\n';
      c += '  85% { filter: ' + dsLR  + '; translate: -' + gs + 'px ' + Math.round(gs*0.5) + 'px; opacity: ' + (op*0.95).toFixed(2) + '; }\n';
      c += '  87% { filter: ' + dsRL  + '; translate: '  + Math.round(gs*0.5) + 'px -' + Math.round(gs*0.25) + 'px; opacity: ' + op + '; }\n';
      c += '  89% { filter: ' + dsLRd + '; translate: -' + Math.round(gs*0.5) + 'px ' + Math.round(gs*0.5) + 'px; opacity: ' + (op*0.90).toFixed(2) + '; }\n';
      c += '  91% { filter: ' + dsLR  + '; translate: '  + gs + 'px 0; opacity: ' + (op*0.93).toFixed(2) + '; }\n';
      c += '  93% { filter: ' + dsRL  + '; translate: -' + Math.round(gs*0.25) + 'px ' + Math.round(gs*0.25) + 'px; opacity: ' + (op*0.97).toFixed(2) + '; }\n}\n';

      c += '@keyframes text-glitch-b {\n';
      c += '  0%, 77%, 79%, 81%, 83%, 85%, 87%, 100% { filter: none; translate: ' + s0 + '; opacity: ' + op + '; }\n';
      c += '  78% { filter: ' + dsRL  + '; translate: '  + gs + 'px -' + Math.round(gs*0.5) + 'px; opacity: ' + (op*0.93).toFixed(2) + '; }\n';
      c += '  80% { filter: ' + dsLRd + '; translate: -' + Math.round(gs*0.5) + 'px ' + Math.round(gs*0.25) + 'px; opacity: ' + op + '; }\n';
      c += '  82% { filter: ' + dsLR  + '; translate: '  + Math.round(gs*0.5) + 'px -' + Math.round(gs*0.5) + 'px; opacity: ' + (op*0.90).toFixed(2) + '; }\n';
      c += '  84% { filter: ' + dsRL  + '; translate: -' + gs + 'px ' + Math.round(gs*0.5) + 'px; opacity: ' + (op*0.93).toFixed(2) + '; }\n';
      c += '  86% { filter: ' + dsLRd + '; translate: '  + Math.round(gs*0.25) + 'px -' + Math.round(gs*0.25) + 'px; opacity: ' + (op*0.97).toFixed(2) + '; }\n}\n';

      if (typing) {
        const tgs = Math.max(gs * 2, 8);
        const tb  = Math.max(cBlur + 2, 5);
        const ca1T = hexToRgba(s.ryzeExtrudeColor, 0.95);
        const ca2T = hexToRgba(s.ryzeGlowColor,    0.95);
        const tLR = 'drop-shadow(-' + tgs + 'px 0 ' + tb + 'px ' + ca1T + ') drop-shadow(' + tgs + 'px 0 ' + tb + 'px ' + ca2T + ')';
        const tRL = 'drop-shadow(' + tgs + 'px 0 ' + tb + 'px ' + ca1T + ') drop-shadow(-' + tgs + 'px 0 ' + tb + 'px ' + ca2T + ')';
        const tM  = 'drop-shadow(-' + Math.round(tgs*0.6) + 'px 0 ' + (tb+2) + 'px ' + ca1d + ') drop-shadow(' + Math.round(tgs*0.6) + 'px 0 ' + (tb+2) + 'px ' + ca2d + ')';
        c += '@keyframes text-glitch-typing {\n';
        c += '  0%   { filter: ' + tLR + '; translate: -' + tgs + 'px ' + Math.round(tgs*0.4) + 'px; }\n';
        c += '  33%  { filter: ' + tRL + '; translate: '  + Math.round(tgs*0.8) + 'px -' + Math.round(tgs*0.3) + 'px; }\n';
        c += '  66%  { filter: ' + tM  + '; translate: -' + Math.round(tgs*0.5) + 'px ' + Math.round(tgs*0.5) + 'px; }\n';
        c += '  100% { filter: none; translate: 0 0; }\n}\n';
        c += 'body.architectus-typing .editor-container .monaco-editor::before {\n';
        c += '  animation: architectus-front var(--architectus-speed) linear infinite' + glitchAnimA + typingAnim + ';\n}\n';
        c += 'body.architectus-typing .editor-container .monaco-editor::after {\n';
        c += '  animation: architectus-back var(--architectus-speed) linear infinite' + glitchAnimB + typingAnim + ';\n}\n';
      }
    }
  }

  return c;
}

function getWebviewHTML(settings, injected) {
  const s = JSON.stringify(settings);
  const injCls = injected ? ' active' : '';
  const injTxt = injected ? 'INJECTED' : 'NOT INJECTED';
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; script-src 'unsafe-inline';">
<style>
:root {
  --bg:    #07100d;
  --s1:    #0c1610;
  --s2:    #101c14;
  --bd:    #1c3028;
  --bd2:   #264038;
  --ac:    #00c4a8;
  --ac2:   #008c78;
  --ac3:   #005c50;
  --gold:  #8a7240;
  --gold2: #b09858;
  --tx:    #c2c0a8;
  --tx2:   #ddd8bc;
  --mu:    #3e5c50;
  --mu2:   #587870;
  --serif: 'Palatino Linotype','Palatino','Book Antiqua',Georgia,serif;
  --mono:  'Courier New',Courier,monospace;
}
*,*::before,*::after { box-sizing: border-box; margin: 0; padding: 0; }

/* Force panel background — overrides any VS Code theme injection */
html, body {
  background-color: var(--bg) !important;
  color: var(--tx) !important;
  /* Override common VS Code theme custom properties */
  --vscode-editor-background:          var(--bg) !important;
  --vscode-sideBar-background:         var(--bg) !important;
  --vscode-panel-background:           var(--bg) !important;
  --vscode-editor-foreground:          var(--tx) !important;
}
body {
  font-family: var(--serif);
  font-size: 12px;
  overflow-x: hidden;
  line-height: 1.5;
}

/* Aged grain — CSS-only, no external resources */
body::after {
  content: '';
  position: fixed; inset: 0;
  background:
    repeating-linear-gradient(
      0deg,
      transparent 0px, transparent 5px,
      rgba(0,196,168,0.012) 5px, rgba(0,196,168,0.012) 6px
    ),
    repeating-linear-gradient(
      90deg,
      transparent 0px, transparent 11px,
      rgba(0,0,0,0.025) 11px, rgba(0,0,0,0.025) 12px
    );
  pointer-events: none;
  z-index: 9999;
}

/* ═══════════════════════════════════
   HEADER  — wanted poster / codex cover
   ═══════════════════════════════════ */
.hdr {
  padding: 14px 14px 12px;
  text-align: center;
  position: relative;
  background-color: var(--s1);
  border-bottom: 1px solid var(--bd);
}

/* Top accent bar */
.hdr::before {
  content: '';
  position: absolute;
  top: 0; left: 0; right: 0; height: 3px;
  background: linear-gradient(90deg,
    transparent 0%,
    var(--ac3) 15%,
    var(--ac)  50%,
    var(--ac3) 85%,
    transparent 100%
  );
}

/* Corner bracket ornaments */
.hdr::after {
  content: '';
  position: absolute;
  inset: 6px;
  border: 1px solid var(--bd2);
  pointer-events: none;
}

.hdr-inner {
  position: relative;
  z-index: 1;
  padding: 4px 8px 2px;
}

.hdr-rule {
  display: flex; align-items: center; gap: 6px;
  margin: 6px 0 4px;
}
.hdr-rule::before,
.hdr-rule::after {
  content: '';
  flex: 1; height: 1px;
  background: linear-gradient(90deg, transparent, var(--ac2));
}
.hdr-rule::after {
  background: linear-gradient(270deg, transparent, var(--ac2));
}
.hdr-gem { color: var(--ac); font-size: 9px; line-height: 1; }

.logo {
  font-family: var(--serif);
  font-size: 18px;
  font-weight: normal;
  letter-spacing: 0.38em;
  color: var(--tx2);
  text-shadow:
    0 0 14px rgba(0,196,168,0.35),
    0 0 36px rgba(0,196,168,0.12);
  line-height: 1;
}

.logo-sub {
  font-family: var(--serif);
  font-size: 8px;
  font-style: italic;
  color: var(--mu2);
  letter-spacing: 0.3em;
  margin-top: 5px;
}

/* ═══════════════════════════════════
   STATUS BAR
   ═══════════════════════════════════ */
.st-bar {
  display: flex; align-items: center; gap: 8px;
  padding: 5px 14px;
  min-height: 24px;
  background-color: var(--bg);
  border-bottom: 1px solid var(--bd);
}
.st-dot {
  width: 5px; height: 5px;
  border-radius: 50%;
  background: var(--mu);
  flex-shrink: 0;
  transition: all 0.4s;
}
.st-txt {
  font-family: var(--mono);
  font-size: 8.5px;
  letter-spacing: 0.14em;
  color: var(--mu);
  text-transform: uppercase;
  transition: color 0.4s;
  flex: 1;
}
.st-bar.on .st-dot { background: var(--ac); box-shadow: 0 0 6px var(--ac); }
.st-bar.on .st-txt  { color: var(--ac); }

/* ═══════════════════════════════════
   ACTION BUTTONS
   ═══════════════════════════════════ */
.act-row {
  display: grid;
  grid-template-columns: 1fr 1fr 1fr;
  background-color: #162420;
  border-bottom: 1px solid var(--bd);
}
.btn {
  padding: 9px 4px;
  border: none; border-right: 1px solid var(--bd);
  background-color: #162420;
  color: var(--mu2);
  cursor: pointer;
  font-family: var(--serif);
  font-size: 9px;
  font-style: italic;
  letter-spacing: 0.12em;
  text-transform: uppercase;
  transition: all 0.15s;
}
.btn:last-child { border-right: none; }
.btn:hover      { background-color: rgba(0,196,168,0.06); color: var(--tx); }
.btn.p          { color: var(--ac); }
.btn.p:hover    { background-color: rgba(0,196,168,0.1); text-shadow: 0 0 10px rgba(0,196,168,0.5); }

.btn-full {
  display: block; width: 100%;
  padding: 8px 14px;
  border: none;
  border-bottom: 1px solid var(--bd);
  background-color: #162420;
  color: var(--mu2);
  cursor: pointer;
  font-family: var(--serif);
  font-size: 9px;
  font-style: italic;
  letter-spacing: 0.1em;
  text-align: center;
  transition: all 0.15s;
}
.btn-full:hover { background-color: rgba(0,196,168,0.1); color: var(--tx2); }
.btn-full::before { content: '— '; color: var(--ac2); font-style: normal; opacity: 0.6; }
.btn-full::after  { content: ' —'; color: var(--ac2); font-style: normal; opacity: 0.6; }

/* ═══════════════════════════════════
   SECTIONS
   ═══════════════════════════════════ */
.sec { border-bottom: 1px solid var(--bd); }

.sec-hdr {
  display: flex; align-items: center; justify-content: space-between;
  padding: 8px 14px;
  cursor: pointer; user-select: none;
  background-color: var(--s1);
  transition: background-color 0.14s;
}
.sec-hdr:hover { background-color: var(--s2); }

.sec-title {
  font-family: var(--serif);
  font-size: 12px;
  font-weight: normal;
  font-style: italic;
  letter-spacing: 0.2em;
  text-transform: uppercase;
  color: var(--tx2);
}
.sec-title::before {
  content: '✶  ';
  font-style: normal;
  color: var(--ac);
  font-size: 7px;
  opacity: 0.85;
}

.chev {
  font-style: normal;
  color: var(--mu2);
  font-size: 8px;
  transition: transform 0.18s;
  display: inline-block;
}
.chev.o { transform: rotate(90deg); }

.sec-body {
  padding: 10px 14px 12px;
  display: flex; flex-direction: column; gap: 8px;
  background-color: var(--bg);
  border-top: 1px solid rgba(0,196,168,0.07);
}
.sec-body.clp { display: none; }

/* Ornamental rule inside each open section */
.sec-body::before {
  content: '― ― ― ◆ ― ― ―';
  display: block;
  text-align: center;
  color: var(--bd2);
  font-size: 7.5px;
  letter-spacing: 0.15em;
  margin-bottom: 2px;
  font-family: var(--serif);
}

/* ═══════════════════════════════════
   FORM ELEMENTS
   ═══════════════════════════════════ */
.row  { display: flex; align-items: center; gap: 8px; }
.lbl  {
  flex: 0 0 82px;
  color: var(--tx);
  font-family: var(--serif);
  font-size: 11px;
  font-style: italic;
}
.inp { flex: 1; min-width: 0; }

/* Text inputs */
input[type=text] {
  width: 100%;
  background-color: var(--s1);
  border: 1px solid var(--bd2);
  border-left: 2px solid var(--ac2);
  color: var(--tx);
  padding: 4px 7px;
  font-size: 10px;
  font-family: var(--mono);
  outline: none;
  border-radius: 0;
  transition: border-color 0.15s;
}
input[type=text]:focus { border-color: var(--ac); border-left-color: var(--ac); }
input[type=text]::placeholder { color: var(--mu); }

/* Sliders */
.sl-row { display: flex; align-items: center; gap: 7px; }
input[type=range] {
  flex: 1; -webkit-appearance: none;
  height: 2px;
  background-color: var(--bd2);
  outline: none; cursor: pointer; border-radius: 0;
}
input[type=range]::-webkit-slider-thumb {
  -webkit-appearance: none;
  width: 10px; height: 10px;
  background-color: var(--s1);
  border: 1px solid var(--ac);
  cursor: pointer; border-radius: 0;
  box-shadow: 0 0 4px rgba(0,196,168,0.35);
  transition: all 0.14s;
}
input[type=range]:hover::-webkit-slider-thumb {
  background-color: var(--ac);
  box-shadow: 0 0 8px rgba(0,196,168,0.6);
}
.sl-val {
  flex: 0 0 36px; text-align: right;
  color: var(--tx2);
  font-family: var(--mono);
  font-size: 10px;
  font-variant-numeric: tabular-nums;
}

/* Color pickers */
.col-row { display: flex; align-items: center; gap: 6px; }
input[type=color] {
  -webkit-appearance: none;
  width: 20px; height: 20px;
  border: 1px solid var(--bd2);
  padding: 0;
  background-color: var(--s1);
  cursor: pointer;
  flex-shrink: 0; border-radius: 0;
}
input[type=color]::-webkit-color-swatch-wrapper { padding: 1px; }
input[type=color]::-webkit-color-swatch { border: none; border-radius: 0; }
.hex {
  width: 68px;
  background-color: var(--s1);
  border: 1px solid var(--bd2);
  color: var(--ac);
  padding: 3px 5px;
  font-size: 9.5px;
  font-family: var(--mono);
  outline: none; border-radius: 0; letter-spacing: 0.04em;
}
.hex:focus { border-color: var(--ac); }

/* Toggles */
.tog { position: relative; width: 30px; height: 14px; flex-shrink: 0; }
.tog input { opacity: 0; width: 0; height: 0; }
.trk {
  position: absolute; inset: 0;
  background-color: var(--s1);
  border: 1px solid var(--bd2);
  border-radius: 0; transition: all 0.2s; cursor: pointer;
}
.trk::after {
  content: ''; position: absolute;
  top: 2px; left: 2px; width: 8px; height: 8px;
  background-color: var(--mu);
  border-radius: 0; transition: all 0.2s;
}
.tog input:checked + .trk { border-color: var(--ac); background-color: rgba(0,196,168,0.08); }
.tog input:checked + .trk::after { transform: translateX(14px); background-color: var(--ac); box-shadow: 0 0 5px var(--ac); }
.tlbl {
  font-family: var(--serif);
  font-size: 11px;
  font-style: italic;
  color: var(--tx);
  cursor: pointer;
}

/* Color grid */
.grid2 { display: grid; grid-template-columns: 1fr 1fr; gap: 7px; }
.col-item { display: flex; flex-direction: column; gap: 3px; }
.col-item-lbl {
  font-family: var(--serif);
  font-size: 10px;
  font-style: italic;
  color: var(--tx);
}

/* Injection status badge */
.inj-status {
  display: flex; align-items: center; justify-content: center; gap: 5px;
  margin-top: 7px;
}
.inj-dot {
  width: 5px; height: 5px; border-radius: 50%;
  background: var(--mu); flex-shrink: 0;
  transition: all 0.4s;
}
.inj-txt {
  font-family: var(--mono); font-size: 8px;
  letter-spacing: 0.2em; color: var(--mu);
  text-transform: uppercase; transition: color 0.4s;
}
.inj-status.active .inj-dot { background: var(--ac); box-shadow: 0 0 6px var(--ac); }
.inj-status.active .inj-txt { color: var(--ac); }
</style>
</head>
<body>

<div class="hdr">
  <div class="hdr-inner">
    <div class="logo">ARCHITECTUS</div>
    <div class="hdr-rule"><span class="hdr-gem">&#10022;</span></div>
    <div class="logo-sub">Control Matrix</div>
    <div class="inj-status${injCls}" id="injStatus">
      <span class="inj-dot"></span>
      <span class="inj-txt" id="injTxt">${injTxt}</span>
    </div>
  </div>
</div>

<div class="st-bar" id="stBar">
  <div class="st-dot"></div>
  <span class="st-txt" id="stTxt">Standby</span>
</div>

<div class="act-row">
  <button class="btn p" id="btnApply">Apply CSS</button>
  <button class="btn"   id="btnReload">Reload</button>
  <button class="btn"   id="btnReset">Reset</button>
</div>
<button class="btn-full" id="btnTheme">Pick Colors from Active Theme</button>

<!-- RYZE Background -->
<div class="sec">
  <div class="sec-hdr" data-sec="ryze">
    <span class="sec-title">Custom Background Text</span>
    <i class="chev o" id="ch-ryze">&#9658;</i>
  </div>
  <div class="sec-body" id="sec-ryze">
    <div class="row">
      <span class="lbl">Enable</span>
      <div class="inp" style="display:flex;align-items:center;gap:8px;">
        <label class="tog"><input type="checkbox" id="ryzeEnabled"><span class="trk"></span></label>
        <span class="tlbl" onclick="document.getElementById('ryzeEnabled').click()">Show background</span>
      </div>
    </div>
    <div class="row">
      <span class="lbl">Front text</span>
      <div class="inp"><input type="text" id="ryzeText" maxlength="20" placeholder="IUDEX"></div>
    </div>
    <div class="row">
      <span class="lbl">Back text</span>
      <div class="inp"><input type="text" id="ryzeBackText" maxlength="20" placeholder="RYZE"></div>
    </div>
    <div class="row">
      <span class="lbl">Opacity</span>
      <div class="inp sl-row">
        <input type="range" id="ryzeOpacity" min="5" max="100" step="5">
        <span class="sl-val" id="ryzeOpacityVal">100%</span>
      </div>
    </div>
    <div class="row">
      <span class="lbl">Speed</span>
      <div class="inp sl-row">
        <input type="range" id="ryzeSpeed" min="1" max="60" step="1">
        <span class="sl-val" id="ryzeSpeedVal">18s</span>
      </div>
    </div>
    <div class="row">
      <span class="lbl">Size</span>
      <div class="inp sl-row">
        <input type="range" id="ryzeSize" min="5" max="30" step="1">
        <span class="sl-val" id="ryzeSizeVal">14vw</span>
      </div>
    </div>
    <div class="row">
      <span class="lbl">Glow color</span>
      <div class="inp col-row">
        <input type="color" id="ryzeGlowColor">
        <input type="text" class="hex" id="ryzeGlowColorHex" maxlength="7">
      </div>
    </div>
    <div class="row">
      <span class="lbl">Extrude</span>
      <div class="inp col-row">
        <input type="color" id="ryzeExtrudeColor">
        <input type="text" class="hex" id="ryzeExtrudeColorHex" maxlength="7">
      </div>
    </div>
    <div class="row">
      <span class="lbl">Glow intens.</span>
      <div class="inp sl-row">
        <input type="range" id="ryzeGlowIntensity" min="0" max="50" step="1">
        <span class="sl-val" id="ryzeGlowIntensityVal">18%</span>
      </div>
    </div>
  </div>
</div>

<!-- Glitch -->
<div class="sec">
  <div class="sec-hdr" data-sec="glitch">
    <span class="sec-title">Glitch</span>
    <i class="chev o" id="ch-glitch">&#9658;</i>
  </div>
  <div class="sec-body" id="sec-glitch">
    <div class="row">
      <span class="lbl">Enable</span>
      <div class="inp" style="display:flex;align-items:center;gap:8px;">
        <label class="tog"><input type="checkbox" id="ryzeGlitchEnabled"><span class="trk"></span></label>
        <span class="tlbl" onclick="document.getElementById('ryzeGlitchEnabled').click()">Text &amp; BG glitch</span>
      </div>
    </div>
    <div class="row">
      <span class="lbl">Type glitch</span>
      <div class="inp" style="display:flex;align-items:center;gap:8px;">
        <label class="tog"><input type="checkbox" id="ryzeTypingGlitch"><span class="trk"></span></label>
        <span class="tlbl" onclick="document.getElementById('ryzeTypingGlitch').click()">Glitch on keypress</span>
      </div>
    </div>
    <div class="row">
      <span class="lbl">Intensity</span>
      <div class="inp sl-row">
        <input type="range" id="ryzeGlitchIntensity" min="0" max="100" step="5">
        <span class="sl-val" id="ryzeGlitchIntensityVal">70%</span>
      </div>
    </div>
    <div class="row">
      <span class="lbl">Frequency</span>
      <div class="inp sl-row">
        <input type="range" id="ryzeGlitchFrequency" min="2" max="30" step="1">
        <span class="sl-val" id="ryzeGlitchFrequencyVal">7s</span>
      </div>
    </div>
  </div>
</div>

<!-- Syntax Colors -->
<div class="sec">
  <div class="sec-hdr" data-sec="syntax">
    <span class="sec-title">Syntax Glow</span>
    <i class="chev o" id="ch-syntax">&#9658;</i>
  </div>
  <div class="sec-body" id="sec-syntax">
    <div class="row">
      <span class="lbl">Glow</span>
      <div class="inp" style="display:flex;align-items:center;gap:8px;">
        <label class="tog"><input type="checkbox" id="syntaxGlowEnabled"><span class="trk"></span></label>
        <span class="tlbl" onclick="document.getElementById('syntaxGlowEnabled').click()">Enable text glow</span>
      </div>
    </div>
    <div class="grid2">
      <div class="col-item">
        <span class="col-item-lbl">Strings</span>
        <div class="col-row"><input type="color" id="colorStrings"><input type="text" class="hex" id="colorStringsHex" maxlength="7"></div>
      </div>
      <div class="col-item">
        <span class="col-item-lbl">Types</span>
        <div class="col-row"><input type="color" id="colorTypes"><input type="text" class="hex" id="colorTypesHex" maxlength="7"></div>
      </div>
      <div class="col-item">
        <span class="col-item-lbl">Keywords</span>
        <div class="col-row"><input type="color" id="colorKeywords"><input type="text" class="hex" id="colorKeywordsHex" maxlength="7"></div>
      </div>
      <div class="col-item">
        <span class="col-item-lbl">Numbers</span>
        <div class="col-row"><input type="color" id="colorNumbers"><input type="text" class="hex" id="colorNumbersHex" maxlength="7"></div>
      </div>
      <div class="col-item">
        <span class="col-item-lbl">Functions</span>
        <div class="col-row"><input type="color" id="colorFunctions"><input type="text" class="hex" id="colorFunctionsHex" maxlength="7"></div>
      </div>
      <div class="col-item">
        <span class="col-item-lbl">Variables</span>
        <div class="col-row"><input type="color" id="colorVariables"><input type="text" class="hex" id="colorVariablesHex" maxlength="7"></div>
      </div>
      <div class="col-item">
        <span class="col-item-lbl">Errors</span>
        <div class="col-row"><input type="color" id="colorErrors"><input type="text" class="hex" id="colorErrorsHex" maxlength="7"></div>
      </div>
      <div class="col-item">
        <span class="col-item-lbl">Comments</span>
        <div class="col-row"><input type="color" id="colorComments"><input type="text" class="hex" id="colorCommentsHex" maxlength="7"></div>
      </div>
    </div>
  </div>
</div>

<!-- Cursor -->
<div class="sec">
  <div class="sec-hdr" data-sec="cursor">
    <span class="sec-title">Cursor</span>
    <i class="chev" id="ch-cursor">&#9658;</i>
  </div>
  <div class="sec-body clp" id="sec-cursor">
    <div class="row">
      <span class="lbl">Primary</span>
      <div class="inp col-row"><input type="color" id="cursorColor1"><input type="text" class="hex" id="cursorColor1Hex" maxlength="7"></div>
    </div>
    <div class="row">
      <span class="lbl">Secondary</span>
      <div class="inp col-row"><input type="color" id="cursorColor2"><input type="text" class="hex" id="cursorColor2Hex" maxlength="7"></div>
    </div>
    <div class="row">
      <span class="lbl">Pulse speed</span>
      <div class="inp sl-row">
        <input type="range" id="cursorPulseSpeed" min="5" max="30" step="1">
        <span class="sl-val" id="cursorPulseSpeedVal">1.4s</span>
      </div>
    </div>
  </div>
</div>

<!-- Effects -->
<div class="sec">
  <div class="sec-hdr" data-sec="effects">
    <span class="sec-title">Effects</span>
    <i class="chev" id="ch-effects">&#9658;</i>
  </div>
  <div class="sec-body clp" id="sec-effects">
    <div class="row">
      <span class="lbl">Scanlines</span>
      <div class="inp" style="display:flex;align-items:center;gap:8px;">
        <label class="tog"><input type="checkbox" id="scanlinesEnabled"><span class="trk"></span></label>
        <span class="tlbl" onclick="document.getElementById('scanlinesEnabled').click()">CRT scanlines</span>
      </div>
    </div>
    <div class="row">
      <span class="lbl">Opacity</span>
      <div class="inp sl-row">
        <input type="range" id="scanlinesOpacity" min="0" max="20" step="1">
        <span class="sl-val" id="scanlinesOpacityVal">6%</span>
      </div>
    </div>
    <div class="row">
      <span class="lbl">Scrollbar</span>
      <div class="inp col-row"><input type="color" id="scrollbarColor"><input type="text" class="hex" id="scrollbarColorHex" maxlength="7"></div>
    </div>
    <div class="row">
      <span class="lbl">Scroll hover</span>
      <div class="inp col-row"><input type="color" id="scrollbarHoverColor"><input type="text" class="hex" id="scrollbarHoverColorHex" maxlength="7"></div>
    </div>
  </div>
</div>

<script>
var vscode = acquireVsCodeApi();
var settings = ${s};

var sliders = [
  { id: 'ryzeOpacity',         key: 'ryzeOpacity',         fmt: function(v){ return v + '%'; } },
  { id: 'ryzeSpeed',           key: 'ryzeSpeed',           fmt: function(v){ return v + 's'; } },
  { id: 'ryzeSize',            key: 'ryzeSize',            fmt: function(v){ return v + 'vw'; } },
  { id: 'ryzeGlowIntensity',   key: 'ryzeGlowIntensity',   fmt: function(v){ return v + '%'; } },
  { id: 'ryzeGlitchIntensity', key: 'ryzeGlitchIntensity', fmt: function(v){ return v + '%'; } },
  { id: 'ryzeGlitchFrequency', key: 'ryzeGlitchFrequency', fmt: function(v){ return v + 's'; } },
  { id: 'cursorPulseSpeed',    key: 'cursorPulseSpeed',    fmt: function(v){ return (v/10).toFixed(1) + 's'; } },
  { id: 'scanlinesOpacity',    key: 'scanlinesOpacity',    fmt: function(v){ return v + '%'; } },
];

var colors = [
  'ryzeGlowColor','ryzeExtrudeColor',
  'colorStrings','colorTypes','colorKeywords','colorNumbers',
  'colorFunctions','colorVariables','colorErrors','colorComments',
  'cursorColor1','cursorColor2','scrollbarColor','scrollbarHoverColor',
];

var toggles = ['ryzeEnabled','scanlinesEnabled','ryzeGlitchEnabled','ryzeTypingGlitch','syntaxGlowEnabled'];
var texts   = ['ryzeText','ryzeBackText'];

function cssColorToHex(color) {
  if (!color) return null;
  color = color.trim();
  if (/^#[0-9a-fA-F]{6}$/.test(color)) return color;
  if (/^#[0-9a-fA-F]{3}$/.test(color)) {
    return '#' + color[1]+color[1]+color[2]+color[2]+color[3]+color[3];
  }
  var m = color.match(/\d+/g);
  if (m && m.length >= 3) {
    return '#' + [m[0],m[1],m[2]].map(function(n){
      return parseInt(n).toString(16).padStart(2,'0');
    }).join('');
  }
  return null;
}

function themeVar(name) {
  return cssColorToHex(getComputedStyle(document.body).getPropertyValue(name));
}

function pickFromTheme() {
  var updates = {
    colorStrings:        themeVar('--vscode-terminal-ansiGreen')         || themeVar('--vscode-charts-green')               || settings.colorStrings,
    colorTypes:          themeVar('--vscode-terminal-ansiCyan')          || themeVar('--vscode-charts-blue')                || settings.colorTypes,
    colorKeywords:       themeVar('--vscode-terminal-ansiMagenta')       || themeVar('--vscode-charts-purple')              || settings.colorKeywords,
    colorNumbers:        themeVar('--vscode-terminal-ansiYellow')        || themeVar('--vscode-charts-yellow')              || settings.colorNumbers,
    colorFunctions:      themeVar('--vscode-terminal-ansiBrightYellow')  || themeVar('--vscode-charts-orange')              || settings.colorFunctions,
    colorVariables:      themeVar('--vscode-terminal-ansiBlue')          || themeVar('--vscode-charts-blue')                || settings.colorVariables,
    colorErrors:         themeVar('--vscode-terminal-ansiRed')           || themeVar('--vscode-charts-red')                 || settings.colorErrors,
    colorComments:       themeVar('--vscode-editorLineNumber-foreground')                                                    || settings.colorComments,
    cursorColor1:        themeVar('--vscode-editorCursor-foreground')    || themeVar('--vscode-focusBorder')                || settings.cursorColor1,
    cursorColor2:        themeVar('--vscode-focusBorder')                || themeVar('--vscode-activityBarBadge-background') || settings.cursorColor2,
    ryzeGlowColor:       themeVar('--vscode-focusBorder')                || themeVar('--vscode-activityBarBadge-background') || settings.ryzeGlowColor,
    ryzeExtrudeColor:    themeVar('--vscode-editorLink-activeForeground')|| themeVar('--vscode-terminal-ansiMagenta')       || settings.ryzeExtrudeColor,
    scrollbarColor:      themeVar('--vscode-scrollbarSlider-background')                                                    || settings.scrollbarColor,
    scrollbarHoverColor: themeVar('--vscode-scrollbarSlider-hoverBackground')                                               || settings.scrollbarHoverColor,
  };
  Object.assign(settings, updates);
  refreshControls();
  save();
  vscode.postMessage({ type: 'apply', settings: settings });
  showStatus('THEME COLORS APPLIED');
}

function showStatus(msg) {
  var bar = document.getElementById('stBar');
  var txt = document.getElementById('stTxt');
  txt.textContent = msg || 'CSS WRITTEN — RELOAD TO APPLY';
  bar.classList.add('on');
  setTimeout(function(){ bar.classList.remove('on'); txt.textContent = 'STANDBY'; }, 3000);
}

function refreshControls() {
  sliders.forEach(function(sl) {
    var el  = document.getElementById(sl.id);
    var val = document.getElementById(sl.id + 'Val');
    el.value = settings[sl.key];
    val.textContent = sl.fmt(settings[sl.key]);
  });
  colors.forEach(function(key) {
    document.getElementById(key).value = settings[key];
    document.getElementById(key + 'Hex').value = settings[key];
  });
  toggles.forEach(function(key) {
    document.getElementById(key).checked = settings[key];
  });
  texts.forEach(function(key) {
    document.getElementById(key).value = settings[key];
  });
}

function init() {
  refreshControls();

  sliders.forEach(function(sl) {
    var el  = document.getElementById(sl.id);
    var val = document.getElementById(sl.id + 'Val');
    el.addEventListener('input', function(e) {
      settings[sl.key] = parseFloat(e.target.value);
      val.textContent = sl.fmt(settings[sl.key]);
      save();
    });
  });

  colors.forEach(function(key) {
    var picker = document.getElementById(key);
    var hex    = document.getElementById(key + 'Hex');
    picker.addEventListener('input', function(e) {
      settings[key] = e.target.value;
      hex.value = e.target.value;
      save();
    });
    hex.addEventListener('input', function(e) {
      if (/^#[0-9a-fA-F]{6}$/.test(e.target.value)) {
        settings[key] = e.target.value;
        picker.value = e.target.value;
        save();
      }
    });
  });

  toggles.forEach(function(key) {
    document.getElementById(key).addEventListener('change', function(e) {
      settings[key] = e.target.checked;
      save();
    });
  });

  texts.forEach(function(key) {
    document.getElementById(key).addEventListener('input', function(e) {
      settings[key] = e.target.value;
      save();
    });
  });

  document.querySelectorAll('.sec-hdr').forEach(function(hdr) {
    hdr.addEventListener('click', function() {
      var sec = hdr.getAttribute('data-sec');
      document.getElementById('sec-' + sec).classList.toggle('clp');
      document.getElementById('ch-' + sec).classList.toggle('o');
    });
  });

  document.getElementById('btnApply').addEventListener('click', function() {
    vscode.postMessage({ type: 'apply', settings: settings });
    showStatus('CSS WRITTEN — RELOAD TO APPLY');
  });
  document.getElementById('btnReload').addEventListener('click', function() {
    vscode.postMessage({ type: 'reload' });
  });
  document.getElementById('btnReset').addEventListener('click', function() {
    vscode.postMessage({ type: 'reset' });
  });
  document.getElementById('btnTheme').addEventListener('click', pickFromTheme);
}

function save() {
  vscode.postMessage({ type: 'save', settings: settings });
}

function setInjected(val) {
  var el  = document.getElementById('injStatus');
  var txt = document.getElementById('injTxt');
  if (val) { el.classList.add('active');    txt.textContent = 'INJECTED'; }
  else      { el.classList.remove('active'); txt.textContent = 'NOT INJECTED'; }
}

window.addEventListener('message', function(e) {
  if (e.data.type === 'settings')  { settings = e.data.settings; refreshControls(); }
  if (e.data.type === 'injected')  { setInjected(e.data.value); }
});

init();
</script>
</body>
</html>`;
}

class ArchitectusProvider {
  constructor(context) {
    this._ctx = context;
    this._view = null;
  }

  resolveWebviewView(webviewView) {
    this._view = webviewView;
    webviewView.webview.options = { enableScripts: true };
    const settings = this._load();
    webviewView.webview.html = getWebviewHTML(settings, isInjected());

    webviewView.webview.onDidReceiveMessage(msg => {
      switch (msg.type) {
        case 'save':
          this._save(msg.settings);
          break;
        case 'apply':
          this._apply(msg.settings);
          break;
        case 'reload':
          this._reload();
          break;
        case 'reset':
          this._reset();
          break;
      }
    });
  }

  _load() {
    const stored = this._ctx.globalState.get('architectusSettings', {});
    return Object.assign({}, DEFAULTS, stored);
  }

  _save(settings) {
    this._ctx.globalState.update('architectusSettings', settings);
  }

  _apply(settings) {
    this._save(settings);
    try {
      fs.writeFileSync(CSS_FILE, generateCSS(settings), 'utf8');
    } catch(e) {
      vscode.window.showErrorMessage('Architectus: Could not write CSS — ' + e.message);
      return;
    }
    vscode.window.showInformationMessage('Architectus: CSS written.');
  }

  _reload() {
    vscode.commands.executeCommand('workbench.action.reloadWindow');
  }

  _reset() {
    this._ctx.globalState.update('architectusSettings', DEFAULTS);
    if (this._view) {
      this._view.webview.postMessage({ type: 'settings', settings: DEFAULTS });
    }
  }
}

function activate(context) {
  const provider = new ArchitectusProvider(context);
  context.subscriptions.push(
    vscode.window.registerWebviewViewProvider('architectus.panel', provider),

    vscode.commands.registerCommand('architectus.enable', () => {
      const s = provider._load();
      try { fs.writeFileSync(CSS_FILE, generateCSS(s), 'utf8'); } catch(e) {
        vscode.window.showErrorMessage('Architectus: ' + e.message); return;
      }
      try { injectCSS(); } catch(e) { showPermissionError(); return; }
      if (provider._view) provider._view.webview.postMessage({ type: 'injected', value: true });
      vscode.window.showInformationMessage('Architectus: Enabled! Reload?', 'Reload').then(c => {
        if (c === 'Reload') vscode.commands.executeCommand('workbench.action.reloadWindow');
      });
    }),

    vscode.commands.registerCommand('architectus.disable', () => {
      try { uninjectCSS(); } catch(e) { showPermissionError(); return; }
      if (provider._view) provider._view.webview.postMessage({ type: 'injected', value: false });
      vscode.window.showInformationMessage('Architectus: Disabled! Reload?', 'Reload').then(c => {
        if (c === 'Reload') vscode.commands.executeCommand('workbench.action.reloadWindow');
      });
    })
  );
}

function deactivate() {}

module.exports = { activate, deactivate };
