'use strict';

const vscode = require('vscode');
const fs = require('fs');
const os = require('os');
const path = require('path');

const CSS_FILE = path.join(os.homedir(), '.vscode', 'varun-architectus.css');

const DEFAULTS = {
  ryzeEnabled: true,
  ryzeText: 'IUDEX',
  ryzeBackText: 'RYZE',
  ryzeOpacity: 100,
  ryzeGlitchEnabled: true,
  ryzeGlitchIntensity: 100,
  ryzeGlitchFrequency: 2,
  ryzeTypingGlitch: true,
  ryzeSpeed: 10,
  ryzeSize: 14,
  ryzePerspective: 900,
  ryzeGlowColor: '#00d4b1',
  ryzeExtrudeColor: '#101116',
  ryzeGlowIntensity: 50,
  colorStrings: '#0059ff',
  colorTypes: '#029790',
  colorKeywords: '#94058a',
  colorNumbers: '#1a1b03',
  colorFunctions: '#d0f30c',
  colorVariables: '#004cf1',
  colorErrors: '#940303',
  colorComments: '#00d4b1',
  cursorColor1: '#00d4b1',
  cursorColor2: '#007fd4',
  cursorPulseSpeed: 5,
  masterEnabled: true,
  syntaxGlowEnabled: true,
  scanlinesEnabled: true,
  scanlinesOpacity: 20,
  scrollbarColor: '#bd93f9',
  scrollbarHoverColor: '#ff79c6',
};

function hexToRgba(hex, alpha) {
  const r = parseInt(hex.slice(1, 3), 16);
  const g = parseInt(hex.slice(3, 5), 16);
  const b = parseInt(hex.slice(5, 7), 16);
  return 'rgba(' + r + ', ' + g + ', ' + b + ', ' + alpha.toFixed(3) + ')';
}

function generateCSS(s) {
  const sc    = (s.scanlinesOpacity / 100).toFixed(3);
  const gi    = s.ryzeGlowIntensity / 100;
  const pulse = (s.cursorPulseSpeed / 10).toFixed(1);
  const op    = ((s.ryzeOpacity || 100) / 100).toFixed(2);
  const front = (s.ryzeText    || 'IUDEX').replace(/\\/g,'\\\\').replace(/"/g,'\\"');
  const back  = (s.ryzeBackText|| 'RYZE' ).replace(/\\/g,'\\\\').replace(/"/g,'\\"');
  const glitch = s.ryzeGlitchEnabled && (s.ryzeGlitchIntensity || 0) > 0;
  const gx    = (s.ryzeGlitchIntensity || 40) / 100;
  const gs    = Math.max(2, Math.round(gx * 8)); // shake / CA offset px
  const cBlur = Math.max(2, Math.round(gx * 6)); // chromatic aberration blur px

  let c = '/* Varun\'s Architectus — generated by Architectus Directives */\n\n';

  c += '/* --- Syntax glow --- */\n';
  if (s.syntaxGlowEnabled !== false) {
    c += '.mtk1  { text-shadow: 0 0 6px rgba(255,255,255,0.6); }\n';
    c += '.mtk3  { text-shadow: 0 0 8px ' + s.colorStrings + ', 0 0 16px ' + s.colorStrings + '; }\n';
    c += '.mtk4  { text-shadow: 0 0 8px ' + s.colorTypes + ', 0 0 16px ' + s.colorTypes + '; }\n';
    c += '.mtk5  { text-shadow: 0 0 8px ' + s.colorKeywords + ', 0 0 14px ' + s.colorKeywords + '; }\n';
    c += '.mtk6  { text-shadow: 0 0 8px ' + s.colorNumbers + ', 0 0 14px ' + s.colorNumbers + '; }\n';
    c += '.mtk7  { text-shadow: 0 0 8px ' + s.colorFunctions + ', 0 0 14px ' + s.colorFunctions + '; }\n';
    c += '.mtk8  { text-shadow: 0 0 6px ' + s.colorVariables + ', 0 0 12px ' + s.colorVariables + '; }\n';
    c += '.mtk9  { text-shadow: 0 0 8px ' + s.colorErrors + ', 0 0 14px ' + s.colorErrors + '; }\n';
    c += '.mtk12 { text-shadow: 0 0 6px ' + s.colorComments + '; }\n';
  } else {
    c += '.mtk1,.mtk3,.mtk4,.mtk5,.mtk6,.mtk7,.mtk8,.mtk9,.mtk12 { text-shadow: none; }\n';
  }
  c += '\n';

  c += '/* --- Cursor --- */\n';
  c += '.cursor { box-shadow: 0 0 6px 2px ' + s.cursorColor1 + ', 0 0 14px 4px ' + s.cursorColor2 + '; animation: cursor-pulse ' + pulse + 's ease-in-out infinite; }\n';
  c += '@keyframes cursor-pulse {\n';
  c += '  0%,100% { box-shadow: 0 0 6px 2px ' + s.cursorColor1 + ', 0 0 14px 4px ' + s.cursorColor2 + '; }\n';
  c += '  50%      { box-shadow: 0 0 12px 4px ' + s.cursorColor1 + ', 0 0 28px 8px ' + s.cursorColor2 + '; }\n}\n\n';

  c += '/* --- Scanlines on editor-container (frees ::after for back-face text) --- */\n';
  c += '.editor-container { position: relative; }\n';
  if (s.scanlinesEnabled) {
    c += '.editor-container::after {\n';
    c += '  content: ""; position: absolute; top: 0; left: 0; right: 0; bottom: 0;\n';
    c += '  background: repeating-linear-gradient(to bottom, transparent 0px, transparent 3px, rgba(0,0,0,' + sc + ') 3px, rgba(0,0,0,' + sc + ') 4px);\n';
    c += '  pointer-events: none; z-index: 100;\n}\n\n';
  }

  // Background glitch
  const bgA1 = hexToRgba(s.ryzeGlowColor, 0.07 * gx);
  const bgA2 = hexToRgba(s.ryzeExtrudeColor, 0.05 * gx);
  if (glitch) {
    c += '/* --- Background glitch --- */\n';
    c += '.editor-container::before {\n';
    c += '  content: ""; position: absolute; top: 0; left: 0; right: 0; bottom: 0;\n';
    c += '  pointer-events: none; z-index: 5; opacity: 0;\n';
    c += '  animation: bg-glitch 11s steps(1) infinite;\n}\n';
    c += '@keyframes bg-glitch {\n';
    c += '  0%, 84%, 92%, 100% { opacity: 0; background: none; }\n';
    c += '  84.5% { opacity: 1; background: linear-gradient(to bottom, transparent 22%, ' + bgA1 + ' 22%, ' + bgA1 + ' 23%, transparent 23%, transparent 58%, ' + bgA2 + ' 58%, ' + bgA2 + ' 59%, transparent 59%); }\n';
    c += '  85.5% { opacity: 0; background: none; }\n';
    c += '  87%   { opacity: 1; background: linear-gradient(to bottom, transparent 71%, ' + bgA1 + ' 71%, ' + bgA1 + ' 73%, transparent 73%); }\n';
    c += '  88%   { opacity: 0; background: none; }\n';
    c += '  90%   { opacity: 1; background: linear-gradient(to bottom, transparent 41%, ' + bgA2 + ' 41%, ' + bgA2 + ' 42%, transparent 42%); }\n';
    c += '  91%   { opacity: 0; background: none; }\n}\n\n';
  }

  c += '/* --- Editor chrome --- */\n';
  c += '.editor-container .monaco-editor { position: relative; }\n';
  c += '.monaco-editor .current-line { box-shadow: inset 0 0 30px ' + hexToRgba(s.ryzeGlowColor, 0.08) + '; border-color: ' + hexToRgba(s.ryzeGlowColor, 0.25) + ' !important; }\n';
  c += '.monaco-scrollable-element > .scrollbar > .slider { background: ' + hexToRgba(s.scrollbarColor, 0.4) + ' !important; border-radius: 4px; box-shadow: 0 0 6px ' + s.scrollbarColor + '; }\n';
  c += '.monaco-scrollable-element > .scrollbar > .slider:hover { background: ' + hexToRgba(s.scrollbarHoverColor, 0.6) + ' !important; box-shadow: 0 0 10px ' + s.scrollbarHoverColor + '; }\n';
  c += '.tab.active { box-shadow: inset 0 -2px 0 ' + s.cursorColor1 + ', 0 0 10px ' + hexToRgba(s.cursorColor1, 0.3) + '; }\n';
  c += '.monaco-list-row.focused { box-shadow: inset 2px 0 0 ' + s.ryzeGlowColor + '; }\n';
  c += '.xterm-cursor-layer .xterm-cursor { box-shadow: 0 0 6px 2px ' + s.colorKeywords + '; }\n';
  c += '.minimap { opacity: 0.6; filter: saturate(1.5) brightness(0.9); }\n\n';

  if (s.ryzeEnabled) {
    const shadow =
      '    1px 1px 0 ' + hexToRgba(s.ryzeExtrudeColor, 0.40) + ',\n' +
      '    2px 2px 0 ' + hexToRgba(s.ryzeExtrudeColor, 0.35) + ',\n' +
      '    3px 3px 0 ' + hexToRgba(s.ryzeExtrudeColor, 0.30) + ',\n' +
      '    4px 4px 0 ' + hexToRgba(s.ryzeExtrudeColor, 0.25) + ',\n' +
      '    5px 5px 0 ' + hexToRgba(s.ryzeExtrudeColor, 0.18) + ',\n' +
      '    6px 6px 0 ' + hexToRgba(s.ryzeExtrudeColor, 0.12) + ',\n' +
      '    7px 7px 0 ' + hexToRgba(s.ryzeGlowColor, 0.08) + ',\n' +
      '    8px 8px 0 ' + hexToRgba(s.ryzeGlowColor, 0.05) + ',\n' +
      '    0 0 40px  ' + hexToRgba(s.ryzeGlowColor, gi) + ',\n' +
      '    0 0 80px  ' + hexToRgba(s.ryzeGlowColor, gi * 0.55) + ',\n' +
      '    0 0 120px ' + hexToRgba(s.ryzeExtrudeColor, gi * 0.33);

    const shared =
      '  position: absolute; top: 50%; left: 50%;\n' +
      '  font-size: clamp(48px,' + s.ryzeSize + 'vw,420px);\n' +
      '  font-weight: 900; font-family: \'Arial Black\',\'Impact\',sans-serif;\n' +
      '  letter-spacing: 0.12em; white-space: nowrap; color: transparent;\n' +
      '  -webkit-text-stroke: 1.5px ' + hexToRgba(s.ryzeGlowColor, 0.35) + ';\n' +
      '  text-shadow:\n' + shadow + ';\n' +
      '  pointer-events: none; z-index: 10; mix-blend-mode: screen; opacity: ' + op + ';\n' +
      '  backface-visibility: hidden; -webkit-backface-visibility: hidden;\n';

    const freq   = s.ryzeGlitchFrequency || 7;
    const freqB  = Math.round(freq * 13 / 9);
    const typing = s.ryzeTypingGlitch;
    const glitchAnimA = glitch ? ', text-glitch-a var(--architectus-freq-a) steps(1) infinite' : '';
    const glitchAnimB = glitch ? ', text-glitch-b var(--architectus-freq-b) steps(1) infinite' : '';
    const typingAnim  = (glitch && typing) ? ', text-glitch-typing 0.22s steps(3) 1' : '';

    c += ':root { --architectus-speed: ' + s.ryzeSpeed + 's;';
    if (glitch) c += ' --architectus-freq-a: ' + freq + 's; --architectus-freq-b: ' + freqB + 's;';
    c += ' }\n';

    c += '/* --- Front/back text flip --- */\n';
    c += '.editor-container .monaco-editor::before,\n.editor-container .monaco-editor::after {\n' + shared + '}\n';
    c += '.editor-container .monaco-editor::before {\n';
    c += '  content: "' + front + '";\n';
    c += '  animation: architectus-front var(--architectus-speed) linear infinite' + glitchAnimA + ';\n}\n';
    c += '.editor-container .monaco-editor::after {\n';
    c += '  content: "' + back + '";\n';
    c += '  animation: architectus-back var(--architectus-speed) linear infinite' + glitchAnimB + ';\n}\n';

    c += '@keyframes architectus-front {\n';
    c += '  from { transform: translate(-50%,-50%) rotateY(0deg); }\n';
    c += '  to   { transform: translate(-50%,-50%) rotateY(360deg); }\n}\n';
    c += '@keyframes architectus-back {\n';
    c += '  from { transform: translate(-50%,-50%) rotateY(180deg); }\n';
    c += '  to   { transform: translate(-50%,-50%) rotateY(540deg); }\n}\n';

    if (glitch) {
      const s0 = '0 0';
      // Chromatic aberration: split extrude color left, glow color right (like the
      // shader's per-segment R/G/B channel offset). Direction alternates per frame.
      // Each jolt frame is immediately followed by a center frame → jolt → center → jolt.
      const ca1 = hexToRgba(s.ryzeExtrudeColor, 0.90);
      const ca2 = hexToRgba(s.ryzeGlowColor,    0.90);
      const ca1d = hexToRgba(s.ryzeExtrudeColor, 0.70);
      const ca2d = hexToRgba(s.ryzeGlowColor,    0.70);
      const b = cBlur;
      const dsLR  = 'drop-shadow(-' + gs + 'px 0 ' + b + 'px ' + ca1 + ') drop-shadow(' + gs + 'px 0 ' + b + 'px ' + ca2 + ')';
      const dsRL  = 'drop-shadow(' + gs + 'px 0 ' + b + 'px ' + ca1 + ') drop-shadow(-' + gs + 'px 0 ' + b + 'px ' + ca2 + ')';
      const dsLRd = 'drop-shadow(-' + Math.round(gs*0.6) + 'px 0 ' + (b+1) + 'px ' + ca1d + ') drop-shadow(' + Math.round(gs*0.6) + 'px 0 ' + (b+1) + 'px ' + ca2d + ')';

      c += '@keyframes text-glitch-a {\n';
      c += '  0%, 84%, 86%, 88%, 90%, 92%, 94%, 100% { filter: none; translate: ' + s0 + '; opacity: ' + op + '; }\n';
      c += '  85% { filter: ' + dsLR  + '; translate: -' + gs + 'px ' + Math.round(gs*0.5) + 'px; opacity: ' + (op*0.95).toFixed(2) + '; }\n';
      c += '  87% { filter: ' + dsRL  + '; translate: '  + Math.round(gs*0.5) + 'px -' + Math.round(gs*0.25) + 'px; opacity: ' + op + '; }\n';
      c += '  89% { filter: ' + dsLRd + '; translate: -' + Math.round(gs*0.5) + 'px ' + Math.round(gs*0.5) + 'px; opacity: ' + (op*0.90).toFixed(2) + '; }\n';
      c += '  91% { filter: ' + dsLR  + '; translate: '  + gs + 'px 0; opacity: ' + (op*0.93).toFixed(2) + '; }\n';
      c += '  93% { filter: ' + dsRL  + '; translate: -' + Math.round(gs*0.25) + 'px ' + Math.round(gs*0.25) + 'px; opacity: ' + (op*0.97).toFixed(2) + '; }\n}\n';

      c += '@keyframes text-glitch-b {\n';
      c += '  0%, 77%, 79%, 81%, 83%, 85%, 87%, 100% { filter: none; translate: ' + s0 + '; opacity: ' + op + '; }\n';
      c += '  78% { filter: ' + dsRL  + '; translate: '  + gs + 'px -' + Math.round(gs*0.5) + 'px; opacity: ' + (op*0.93).toFixed(2) + '; }\n';
      c += '  80% { filter: ' + dsLRd + '; translate: -' + Math.round(gs*0.5) + 'px ' + Math.round(gs*0.25) + 'px; opacity: ' + op + '; }\n';
      c += '  82% { filter: ' + dsLR  + '; translate: '  + Math.round(gs*0.5) + 'px -' + Math.round(gs*0.5) + 'px; opacity: ' + (op*0.90).toFixed(2) + '; }\n';
      c += '  84% { filter: ' + dsRL  + '; translate: -' + gs + 'px ' + Math.round(gs*0.5) + 'px; opacity: ' + (op*0.93).toFixed(2) + '; }\n';
      c += '  86% { filter: ' + dsLRd + '; translate: '  + Math.round(gs*0.25) + 'px -' + Math.round(gs*0.25) + 'px; opacity: ' + (op*0.97).toFixed(2) + '; }\n}\n';

      if (typing) {
        const tgs = Math.max(gs * 2, 8);
        const tb  = Math.max(cBlur + 2, 5);
        const ca1T = hexToRgba(s.ryzeExtrudeColor, 0.95);
        const ca2T = hexToRgba(s.ryzeGlowColor,    0.95);
        const tLR = 'drop-shadow(-' + tgs + 'px 0 ' + tb + 'px ' + ca1T + ') drop-shadow(' + tgs + 'px 0 ' + tb + 'px ' + ca2T + ')';
        const tRL = 'drop-shadow(' + tgs + 'px 0 ' + tb + 'px ' + ca1T + ') drop-shadow(-' + tgs + 'px 0 ' + tb + 'px ' + ca2T + ')';
        const tM  = 'drop-shadow(-' + Math.round(tgs*0.6) + 'px 0 ' + (tb+2) + 'px ' + ca1d + ') drop-shadow(' + Math.round(tgs*0.6) + 'px 0 ' + (tb+2) + 'px ' + ca2d + ')';
        c += '@keyframes text-glitch-typing {\n';
        c += '  0%   { filter: ' + tLR + '; translate: -' + tgs + 'px ' + Math.round(tgs*0.4) + 'px; }\n';
        c += '  33%  { filter: ' + tRL + '; translate: '  + Math.round(tgs*0.8) + 'px -' + Math.round(tgs*0.3) + 'px; }\n';
        c += '  66%  { filter: ' + tM  + '; translate: -' + Math.round(tgs*0.5) + 'px ' + Math.round(tgs*0.5) + 'px; }\n';
        c += '  100% { filter: none; translate: 0 0; }\n}\n';
        c += 'body.architectus-typing .editor-container .monaco-editor::before {\n';
        c += '  animation: architectus-front var(--architectus-speed) linear infinite' + glitchAnimA + typingAnim + ';\n}\n';
        c += 'body.architectus-typing .editor-container .monaco-editor::after {\n';
        c += '  animation: architectus-back var(--architectus-speed) linear infinite' + glitchAnimB + typingAnim + ';\n}\n';
      }
    }
  }

  return c;
}

function getWebviewHTML(settings, extra) {
  const s = JSON.stringify(settings);
  const masterChk = settings.masterEnabled !== false ? 'checked' : '';
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; script-src 'unsafe-inline';">
<style>
:root {
  --bg:    #07100d;
  --s1:    #0c1610;
  --s2:    #101c14;
  --bd:    #1c3028;
  --bd2:   #264038;
  --ac:    #00c4a8;
  --ac2:   #008c78;
  --ac3:   #005c50;
  --gold:  #8a7240;
  --gold2: #b09858;
  --tx:    #c2c0a8;
  --tx2:   #ddd8bc;
  --mu:    #3e5c50;
  --mu2:   #587870;
  --serif: 'Palatino Linotype','Palatino','Book Antiqua',Georgia,serif;
  --mono:  'Courier New',Courier,monospace;
}
*,*::before,*::after { box-sizing: border-box; margin: 0; padding: 0; }

/* Force panel background — overrides any VS Code theme injection */
html, body {
  background-color: var(--bg) !important;
  color: var(--tx) !important;
  /* Override common VS Code theme custom properties */
  --vscode-editor-background:          var(--bg) !important;
  --vscode-sideBar-background:         var(--bg) !important;
  --vscode-panel-background:           var(--bg) !important;
  --vscode-editor-foreground:          var(--tx) !important;
}
body {
  font-family: var(--serif);
  font-size: 12px;
  overflow-x: hidden;
  line-height: 1.5;
}

/* Aged grain — CSS-only, no external resources */
body::after {
  content: '';
  position: fixed; inset: 0;
  background:
    repeating-linear-gradient(
      0deg,
      transparent 0px, transparent 5px,
      rgba(0,196,168,0.012) 5px, rgba(0,196,168,0.012) 6px
    ),
    repeating-linear-gradient(
      90deg,
      transparent 0px, transparent 11px,
      rgba(0,0,0,0.025) 11px, rgba(0,0,0,0.025) 12px
    );
  pointer-events: none;
  z-index: 9999;
}

/* ═══════════════════════════════════
   HEADER  — wanted poster / codex cover
   ═══════════════════════════════════ */
.hdr {
  padding: 14px 14px 12px;
  text-align: center;
  position: relative;
  background-color: var(--s1);
  border-bottom: 1px solid var(--bd);
}

/* Top accent bar */
.hdr::before {
  content: '';
  position: absolute;
  top: 0; left: 0; right: 0; height: 3px;
  background: linear-gradient(90deg,
    transparent 0%,
    var(--ac3) 15%,
    var(--ac)  50%,
    var(--ac3) 85%,
    transparent 100%
  );
}

/* Corner bracket ornaments */
.hdr::after {
  content: '';
  position: absolute;
  inset: 6px;
  border: 1px solid var(--bd2);
  pointer-events: none;
}

.hdr-inner {
  position: relative;
  z-index: 1;
  padding: 4px 8px 2px;
}

.hdr-rule {
  display: flex; align-items: center; gap: 6px;
  margin: 6px 0 4px;
}
.hdr-rule::before,
.hdr-rule::after {
  content: '';
  flex: 1; height: 1px;
  background: linear-gradient(90deg, transparent, var(--ac2));
}
.hdr-rule::after {
  background: linear-gradient(270deg, transparent, var(--ac2));
}
.hdr-gem { color: var(--ac); font-size: 9px; line-height: 1; }

.logo {
  font-family: var(--serif);
  font-size: 18px;
  font-weight: normal;
  letter-spacing: 0.38em;
  color: var(--tx2);
  text-shadow:
    0 0 14px rgba(0,196,168,0.35),
    0 0 36px rgba(0,196,168,0.12);
  line-height: 1;
}

.logo-sub {
  font-family: var(--serif);
  font-size: 8px;
  font-style: italic;
  color: var(--mu2);
  letter-spacing: 0.3em;
  margin-top: 5px;
}

/* ═══════════════════════════════════
   STATUS BAR
   ═══════════════════════════════════ */
.st-bar {
  display: flex; align-items: center; gap: 8px;
  padding: 5px 14px;
  min-height: 24px;
  background-color: var(--bg);
  border-bottom: 1px solid var(--bd);
}
.st-dot {
  width: 5px; height: 5px;
  border-radius: 50%;
  background: var(--mu);
  flex-shrink: 0;
  transition: all 0.4s;
}
.st-txt {
  font-family: var(--mono);
  font-size: 8.5px;
  letter-spacing: 0.14em;
  color: var(--mu);
  text-transform: uppercase;
  transition: color 0.4s;
  flex: 1;
}
.st-bar.on .st-dot { background: var(--ac); box-shadow: 0 0 6px var(--ac); }
.st-bar.on .st-txt  { color: var(--ac); }

/* ═══════════════════════════════════
   ACTION BUTTONS
   ═══════════════════════════════════ */
.act-row {
  display: grid;
  grid-template-columns: 1fr 1fr 1fr;
  background-color: #162420;
  border-bottom: 1px solid var(--bd);
}
.btn {
  padding: 9px 4px;
  border: none; border-right: 1px solid var(--bd);
  background-color: #162420;
  color: var(--mu2);
  cursor: pointer;
  font-family: var(--serif);
  font-size: 9px;
  font-style: italic;
  letter-spacing: 0.12em;
  text-transform: uppercase;
  transition: all 0.15s;
}
.btn:last-child { border-right: none; }
.btn:hover      { background-color: rgba(0,196,168,0.06); color: var(--tx); }
.btn.p          { color: var(--ac); }
.btn.p:hover    { background-color: rgba(0,196,168,0.1); text-shadow: 0 0 10px rgba(0,196,168,0.5); }

.btn-full {
  display: block; width: 100%;
  padding: 8px 14px;
  border: none;
  border-bottom: 1px solid var(--bd);
  background-color: #162420;
  color: var(--mu2);
  cursor: pointer;
  font-family: var(--serif);
  font-size: 9px;
  font-style: italic;
  letter-spacing: 0.1em;
  text-align: center;
  transition: all 0.15s;
}
.btn-full:hover { background-color: rgba(0,196,168,0.1); color: var(--tx2); }
.btn-full::before { content: '— '; color: var(--ac2); font-style: normal; opacity: 0.6; }
.btn-full::after  { content: ' —'; color: var(--ac2); font-style: normal; opacity: 0.6; }

/* ═══════════════════════════════════
   SECTIONS
   ═══════════════════════════════════ */
.sec { border-bottom: 1px solid var(--bd); }

.sec-hdr {
  display: flex; align-items: center; justify-content: space-between;
  padding: 8px 14px;
  cursor: pointer; user-select: none;
  background-color: var(--s1);
  transition: background-color 0.14s;
}
.sec-hdr:hover { background-color: var(--s2); }

.sec-title {
  font-family: var(--serif);
  font-size: 12px;
  font-weight: normal;
  font-style: italic;
  letter-spacing: 0.2em;
  text-transform: uppercase;
  color: var(--tx2);
}
.sec-title::before {
  content: '✶  ';
  font-style: normal;
  color: var(--ac);
  font-size: 7px;
  opacity: 0.85;
}

.chev {
  font-style: normal;
  color: var(--mu2);
  font-size: 8px;
  transition: transform 0.18s;
  display: inline-block;
}
.chev.o { transform: rotate(90deg); }

.sec-body {
  padding: 10px 14px 12px;
  display: flex; flex-direction: column; gap: 8px;
  background-color: var(--bg);
  border-top: 1px solid rgba(0,196,168,0.07);
}
.sec-body.clp { display: none; }

/* Ornamental rule inside each open section */
.sec-body::before {
  content: '― ― ― ◆ ― ― ―';
  display: block;
  text-align: center;
  color: var(--bd2);
  font-size: 7.5px;
  letter-spacing: 0.15em;
  margin-bottom: 2px;
  font-family: var(--serif);
}

/* ═══════════════════════════════════
   FORM ELEMENTS
   ═══════════════════════════════════ */
.row  { display: flex; align-items: center; gap: 8px; }
.lbl  {
  flex: 0 0 82px;
  color: var(--tx);
  font-family: var(--serif);
  font-size: 11px;
  font-style: italic;
}
.inp { flex: 1; min-width: 0; }

/* Text inputs */
input[type=text] {
  width: 100%;
  background-color: var(--s1);
  border: 1px solid var(--bd2);
  border-left: 2px solid var(--ac2);
  color: var(--tx);
  padding: 4px 7px;
  font-size: 10px;
  font-family: var(--mono);
  outline: none;
  border-radius: 0;
  transition: border-color 0.15s;
}
input[type=text]:focus { border-color: var(--ac); border-left-color: var(--ac); }
input[type=text]::placeholder { color: var(--mu); }

/* Sliders */
.sl-row { display: flex; align-items: center; gap: 7px; }
input[type=range] {
  flex: 1; -webkit-appearance: none;
  height: 2px;
  background-color: var(--bd2);
  outline: none; cursor: pointer; border-radius: 0;
}
input[type=range]::-webkit-slider-thumb {
  -webkit-appearance: none;
  width: 10px; height: 10px;
  background-color: var(--s1);
  border: 1px solid var(--ac);
  cursor: pointer; border-radius: 0;
  box-shadow: 0 0 4px rgba(0,196,168,0.35);
  transition: all 0.14s;
}
input[type=range]:hover::-webkit-slider-thumb {
  background-color: var(--ac);
  box-shadow: 0 0 8px rgba(0,196,168,0.6);
}
.sl-val {
  flex: 0 0 36px; text-align: right;
  color: var(--tx2);
  font-family: var(--mono);
  font-size: 10px;
  font-variant-numeric: tabular-nums;
}

/* Color pickers */
.col-row { display: flex; align-items: center; gap: 6px; }
input[type=color] {
  -webkit-appearance: none;
  width: 20px; height: 20px;
  border: 1px solid var(--bd2);
  padding: 0;
  background-color: var(--s1);
  cursor: pointer;
  flex-shrink: 0; border-radius: 0;
}
input[type=color]::-webkit-color-swatch-wrapper { padding: 1px; }
input[type=color]::-webkit-color-swatch { border: none; border-radius: 0; }
.hex {
  width: 68px;
  background-color: var(--s1);
  border: 1px solid var(--bd2);
  color: var(--ac);
  padding: 3px 5px;
  font-size: 9.5px;
  font-family: var(--mono);
  outline: none; border-radius: 0; letter-spacing: 0.04em;
}
.hex:focus { border-color: var(--ac); }

/* Toggles */
.tog { position: relative; width: 30px; height: 14px; flex-shrink: 0; }
.tog input { opacity: 0; width: 0; height: 0; }
.trk {
  position: absolute; inset: 0;
  background-color: var(--s1);
  border: 1px solid var(--bd2);
  border-radius: 0; transition: all 0.2s; cursor: pointer;
}
.trk::after {
  content: ''; position: absolute;
  top: 2px; left: 2px; width: 8px; height: 8px;
  background-color: var(--mu);
  border-radius: 0; transition: all 0.2s;
}
.tog input:checked + .trk { border-color: var(--ac); background-color: rgba(0,196,168,0.08); }
.tog input:checked + .trk::after { transform: translateX(14px); background-color: var(--ac); box-shadow: 0 0 5px var(--ac); }
.tlbl {
  font-family: var(--serif);
  font-size: 11px;
  font-style: italic;
  color: var(--tx);
  cursor: pointer;
}

/* Color grid */
.grid2 { display: grid; grid-template-columns: 1fr 1fr; gap: 7px; }
.col-item { display: flex; flex-direction: column; gap: 3px; }
.col-item-lbl {
  font-family: var(--serif);
  font-size: 10px;
  font-style: italic;
  color: var(--tx);
}

/* ═══════════════════════════════════
   QUICK COMMANDS
   ═══════════════════════════════════ */
.qc-list { display: flex; flex-direction: column; gap: 5px; }
.qc-item { display: flex; align-items: center; gap: 6px; }
.qc-lbl  { flex: 1; font-family: var(--serif); font-size: 11px; font-style: italic; color: var(--tx); overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
.qc-run  { padding: 3px 8px; background: rgba(0,196,168,0.08); border: 1px solid var(--ac2); color: var(--ac); font-family: var(--mono); font-size: 9px; letter-spacing: 0.1em; cursor: pointer; transition: all 0.14s; }
.qc-run:hover { background: rgba(0,196,168,0.18); box-shadow: 0 0 6px rgba(0,196,168,0.3); }
.qc-del  { padding: 3px 6px; background: none; border: 1px solid var(--bd2); color: var(--mu); font-size: 9px; cursor: pointer; transition: all 0.14s; }
.qc-del:hover { border-color: #7a2020; color: #c05050; }
.qc-add  { display: flex; gap: 5px; margin-top: 8px; padding-top: 8px; border-top: 1px solid var(--bd); }
.qc-add input { flex: 1; min-width: 0; }
.qc-add-btn { padding: 4px 10px; background: rgba(0,196,168,0.08); border: 1px solid var(--ac2); color: var(--ac); font-family: var(--mono); font-size: 11px; cursor: pointer; flex-shrink: 0; transition: all 0.14s; }
.qc-add-btn:hover { background: rgba(0,196,168,0.18); }
.qc-empty { font-family: var(--serif); font-size: 10px; font-style: italic; color: var(--mu); text-align: center; padding: 6px 0; }

/* ═══════════════════════════════════
   FONT CONTROLS
   ═══════════════════════════════════ */
.font-reset { display: block; width: 100%; margin-top: 6px; padding: 6px; background: none; border: 1px solid var(--bd2); color: var(--mu); font-family: var(--serif); font-size: 10px; font-style: italic; letter-spacing: 0.1em; cursor: pointer; transition: all 0.14s; }
.font-reset:hover { border-color: var(--ac2); color: var(--tx); }

/* ═══════════════════════════════════
   SCRATCH PAD
   ═══════════════════════════════════ */
.scratch-wrap { display: flex; flex-direction: column; gap: 5px; }
.scratch-area {
  width: 100%; min-height: 110px; resize: vertical;
  background: var(--s1); border: 1px solid var(--bd2); border-left: 2px solid var(--ac2);
  color: var(--tx); padding: 7px 8px;
  font-family: var(--mono); font-size: 11px; line-height: 1.55;
  outline: none; border-radius: 0; box-sizing: border-box;
}
.scratch-area:focus { border-color: var(--ac); border-left-color: var(--ac); }
.scratch-area::placeholder { color: var(--mu); }
.scratch-meta { font-family: var(--mono); font-size: 8px; color: var(--mu); text-align: right; letter-spacing: 0.08em; }

/* ═══════════════════════════════════
   COLOR TOOLS
   ═══════════════════════════════════ */
.ct-preview { width: 100%; height: 36px; border: 1px solid var(--bd2); margin-bottom: 8px; cursor: pointer; }
.ct-picker-row { display: flex; align-items: center; gap: 8px; margin-bottom: 10px; }
.ct-picker-lbl { font-family: var(--serif); font-size: 11px; font-style: italic; color: var(--tx); }
.ct-row { display: flex; align-items: center; gap: 6px; margin-bottom: 5px; }
.ct-fmt  { flex: 0 0 30px; font-family: var(--mono); font-size: 8.5px; color: var(--mu); letter-spacing: 0.1em; text-transform: uppercase; }
.ct-val  { flex: 1; font-family: var(--mono); font-size: 10px; color: var(--tx2); overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
.ct-copy { padding: 2px 8px; background: none; border: 1px solid var(--bd2); color: var(--mu); font-family: var(--mono); font-size: 8px; letter-spacing: 0.08em; cursor: pointer; transition: all 0.14s; }
.ct-copy:hover { border-color: var(--ac2); color: var(--ac); }
.ct-copy.flash { border-color: var(--ac); color: var(--ac); box-shadow: 0 0 6px rgba(0,196,168,0.4); }

/* ═══════════════════════════════════
   PATH UTILS
   ═══════════════════════════════════ */
.pu-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 6px; margin-top: 4px; }
.pu-btn { padding: 7px 4px; background: rgba(0,196,168,0.06); border: 1px solid var(--bd2); color: var(--tx); font-family: var(--serif); font-size: 10px; font-style: italic; letter-spacing: 0.08em; cursor: pointer; transition: all 0.14s; text-align: center; }
.pu-btn:hover { border-color: var(--ac2); color: var(--ac); background: rgba(0,196,168,0.12); }
.pu-info { font-family: var(--mono); font-size: 9px; color: var(--mu); margin-top: 7px; word-break: break-all; line-height: 1.55; }

/* ═══════════════════════════════════
   TODO SCANNER
   ═══════════════════════════════════ */
.todo-scan-btn { display: block; width: 100%; padding: 7px; background: rgba(0,196,168,0.06); border: 1px solid var(--bd2); color: var(--tx); font-family: var(--serif); font-size: 10px; font-style: italic; letter-spacing: 0.1em; cursor: pointer; margin-bottom: 8px; transition: all 0.14s; }
.todo-scan-btn:hover { border-color: var(--ac); color: var(--ac); }
.todo-list { display: flex; flex-direction: column; gap: 4px; max-height: 220px; overflow-y: auto; }
.todo-item { display: flex; flex-direction: column; gap: 2px; padding: 5px 7px; background: var(--s1); border-left: 2px solid var(--bd2); cursor: pointer; transition: border-color 0.14s; }
.todo-item:hover { border-left-color: var(--ac2); }
.todo-item-hdr { display: flex; align-items: center; gap: 6px; }
.todo-tag { font-family: var(--mono); font-size: 8px; font-weight: bold; letter-spacing: 0.1em; padding: 1px 5px; border: 1px solid; flex-shrink: 0; }
.todo-tag.TODO  { color: #f1c40f; border-color: #f1c40f; }
.todo-tag.FIXME { color: #e74c3c; border-color: #e74c3c; }
.todo-tag.HACK  { color: #e67e22; border-color: #e67e22; }
.todo-tag.NOTE  { color: #3498db; border-color: #3498db; }
.todo-tag.XXX   { color: #9b59b6; border-color: #9b59b6; }
.todo-loc { font-family: var(--mono); font-size: 9px; color: var(--mu2); flex: 1; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
.todo-txt { font-family: var(--mono); font-size: 9.5px; color: var(--tx); line-height: 1.4; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
.todo-empty { font-family: var(--serif); font-size: 10px; font-style: italic; color: var(--mu); text-align: center; padding: 10px 0; }

/* ═══════════════════════════════════
   GIT QUICK ACTIONS
   ═══════════════════════════════════ */
.git-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 6px; }
.git-btn { padding: 7px 4px; background: rgba(0,196,168,0.06); border: 1px solid var(--bd2); color: var(--tx); font-family: var(--mono); font-size: 9px; letter-spacing: 0.1em; cursor: pointer; transition: all 0.14s; text-align: center; }
.git-btn:hover { border-color: var(--ac2); color: var(--ac); background: rgba(0,196,168,0.12); }
.git-commit-row { display: flex; gap: 5px; margin-top: 8px; padding-top: 8px; border-top: 1px solid var(--bd); }
.git-commit-row input { flex: 1; }
.git-commit-btn { padding: 4px 10px; background: rgba(0,196,168,0.08); border: 1px solid var(--ac2); color: var(--ac); font-family: var(--mono); font-size: 9px; letter-spacing: 0.08em; cursor: pointer; flex-shrink: 0; transition: all 0.14s; }
.git-commit-btn:hover { background: rgba(0,196,168,0.18); }

/* ═══════════════════════════════════
   SNIPPET BANK
   ═══════════════════════════════════ */
.snip-list { display: flex; flex-direction: column; gap: 5px; }
.snip-item { display: flex; align-items: center; gap: 6px; }
.snip-lbl  { flex: 1; font-family: var(--serif); font-size: 11px; font-style: italic; color: var(--tx); overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
.snip-ins  { padding: 3px 8px; background: rgba(0,196,168,0.08); border: 1px solid var(--ac2); color: var(--ac); font-family: var(--mono); font-size: 9px; letter-spacing: 0.1em; cursor: pointer; transition: all 0.14s; }
.snip-ins:hover { background: rgba(0,196,168,0.18); box-shadow: 0 0 6px rgba(0,196,168,0.3); }
.snip-del  { padding: 3px 6px; background: none; border: 1px solid var(--bd2); color: var(--mu); font-size: 9px; cursor: pointer; transition: all 0.14s; }
.snip-del:hover { border-color: #7a2020; color: #c05050; }
.snip-add-wrap { margin-top: 8px; padding-top: 8px; border-top: 1px solid var(--bd); display: flex; flex-direction: column; gap: 5px; }
.snip-add-body { width: 100%; min-height: 60px; resize: vertical; background: var(--s1); border: 1px solid var(--bd2); border-left: 2px solid var(--ac2); color: var(--tx); padding: 6px 8px; font-family: var(--mono); font-size: 10px; outline: none; box-sizing: border-box; }
.snip-add-body:focus { border-color: var(--ac); border-left-color: var(--ac); }
.snip-add-body::placeholder { color: var(--mu); }
.snip-add-footer { display: flex; gap: 5px; }
.snip-add-btn { padding: 4px 10px; background: rgba(0,196,168,0.08); border: 1px solid var(--ac2); color: var(--ac); font-family: var(--mono); font-size: 9px; cursor: pointer; flex-shrink: 0; transition: all 0.14s; }
.snip-add-btn:hover { background: rgba(0,196,168,0.18); }
.snip-empty { font-family: var(--serif); font-size: 10px; font-style: italic; color: var(--mu); text-align: center; padding: 6px 0; }

/* ═══════════════════════════════════
   TEXT TRANSFORM
   ═══════════════════════════════════ */
.tt-area { width: 100%; min-height: 70px; resize: vertical; background: var(--s1); border: 1px solid var(--bd2); border-left: 2px solid var(--ac2); color: var(--tx); padding: 7px 8px; font-family: var(--mono); font-size: 11px; outline: none; box-sizing: border-box; margin-bottom: 8px; }
.tt-area:focus { border-color: var(--ac); border-left-color: var(--ac); }
.tt-area::placeholder { color: var(--mu); }
.tt-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 5px; margin-bottom: 8px; }
.tt-btn { padding: 6px 4px; background: rgba(0,196,168,0.06); border: 1px solid var(--bd2); color: var(--tx); font-family: var(--mono); font-size: 8.5px; letter-spacing: 0.06em; cursor: pointer; transition: all 0.14s; text-align: center; }
.tt-btn:hover { border-color: var(--ac2); color: var(--ac); background: rgba(0,196,168,0.12); }
.tt-out-lbl { font-family: var(--serif); font-size: 10px; font-style: italic; color: var(--mu); margin-bottom: 4px; }
.tt-copy-row { display: flex; gap: 5px; margin-top: 5px; }
.tt-copy-btn { padding: 3px 10px; background: none; border: 1px solid var(--bd2); color: var(--mu); font-family: var(--mono); font-size: 8px; cursor: pointer; transition: all 0.14s; }
.tt-copy-btn:hover { border-color: var(--ac2); color: var(--ac); }

/* ═══════════════════════════════════
   TIMESTAMP TOOLS
   ═══════════════════════════════════ */
.ts-now { font-family: var(--mono); font-size: 9.5px; color: var(--ac); letter-spacing: 0.06em; padding: 5px 0; margin-bottom: 8px; border-bottom: 1px solid var(--bd); line-height: 1.6; }
.ts-conv-row { display: flex; align-items: center; gap: 5px; margin-bottom: 5px; }
.ts-conv-row input { flex: 1; }
.ts-conv-btn { padding: 4px 9px; background: rgba(0,196,168,0.06); border: 1px solid var(--bd2); color: var(--tx); font-family: var(--mono); font-size: 9px; cursor: pointer; flex-shrink: 0; transition: all 0.14s; white-space: nowrap; }
.ts-conv-btn:hover { border-color: var(--ac2); color: var(--ac); }
.ts-result { font-family: var(--mono); font-size: 9.5px; color: var(--tx2); padding: 5px 7px; background: var(--s1); border-left: 2px solid var(--ac2); margin-bottom: 4px; word-break: break-all; min-height: 28px; line-height: 1.6; }
.ts-copy-btn { padding: 2px 8px; background: none; border: 1px solid var(--bd2); color: var(--mu); font-family: var(--mono); font-size: 8px; cursor: pointer; margin-bottom: 10px; transition: all 0.14s; }
.ts-copy-btn:hover { border-color: var(--ac2); color: var(--ac); }

/* ═══════════════════════════════════
   REGEX TESTER
   ═══════════════════════════════════ */
.rx-row { margin-bottom: 6px; }
.rx-lbl { font-family: var(--serif); font-size: 10px; font-style: italic; color: var(--mu); margin-bottom: 3px; display: block; }
.rx-pat-row { display: flex; gap: 5px; }
.rx-pat-row input { flex: 1; }
.rx-flags { width: 46px !important; flex: 0 0 46px !important; }
.rx-test { width: 100%; min-height: 60px; resize: vertical; background: var(--s1); border: 1px solid var(--bd2); border-left: 2px solid var(--ac2); color: var(--tx); padding: 7px 8px; font-family: var(--mono); font-size: 11px; outline: none; box-sizing: border-box; }
.rx-test:focus { border-color: var(--ac); border-left-color: var(--ac); }
.rx-test::placeholder { color: var(--mu); }
.rx-results { margin-top: 8px; padding: 6px 8px; background: var(--s1); border: 1px solid var(--bd2); min-height: 36px; font-family: var(--mono); font-size: 10px; color: var(--tx); line-height: 1.8; word-break: break-all; }
.rx-match { background: rgba(0,196,168,0.15); border: 1px solid rgba(0,196,168,0.35); padding: 1px 4px; margin: 1px; display: inline-block; }
.rx-no-match { color: var(--mu); font-style: italic; }
.rx-error { color: #e74c3c; font-style: italic; }
.rx-count { font-family: var(--serif); font-size: 9px; font-style: italic; color: var(--mu); margin-top: 5px; }

/* Master section — top-level collapsible module */
.msec { border-bottom: 1px solid var(--bd2); }

.msec-hdr {
  display: flex; align-items: center; justify-content: space-between;
  padding: 10px 14px;
  cursor: default;
  background: linear-gradient(90deg, var(--s2), rgba(0,196,168,0.04));
  border-bottom: 1px solid var(--bd2);
  border-top: 1px solid rgba(0,196,168,0.12);
}
.msec-hdr-left {
  display: flex; align-items: center; gap: 9px;
  cursor: pointer; user-select: none; flex: 1;
}
.msec-title {
  font-family: var(--mono);
  font-size: 10px; font-weight: normal;
  letter-spacing: 0.22em; text-transform: uppercase;
  color: var(--ac);
}
.msec-body { }
.msec-body.clp { display: none; }

</style>
</head>
<body>

<div class="hdr">
  <div class="hdr-inner">
    <div class="logo">ARCHITECTUS</div>
    <div class="hdr-rule"><span class="hdr-gem">&#10022;</span></div>
    <div class="logo-sub">Developer Toolkit</div>
  </div>
</div>

<div class="st-bar" id="stBar">
  <div class="st-dot"></div>
  <span class="st-txt" id="stTxt">Standby</span>
</div>

<div class="act-row">
  <button class="btn p" id="btnApply">Apply CSS</button>
  <button class="btn"   id="btnReload">Reload</button>
  <button class="btn"   id="btnReset">Reset</button>
</div>
<button class="btn-full" id="btnTheme">Pick Colors from Active Theme</button>

<!-- BACKGROUND CONSOLE master section -->
<div class="msec">
  <div class="msec-hdr">
    <div class="msec-hdr-left" id="masterHdr">
      <i class="chev o" id="ch-master">&#9658;</i>
      <span class="msec-title">Background Console</span>
    </div>
    <label class="tog" title="Enable / disable injection">
      <input type="checkbox" id="masterEnabled" ${masterChk}>
      <span class="trk"></span>
    </label>
  </div>
  <div class="msec-body" id="sec-master">

<!-- RYZE Background -->
<div class="sec">
  <div class="sec-hdr" data-sec="ryze">
    <span class="sec-title">Custom Background Text</span>
    <i class="chev o" id="ch-ryze">&#9658;</i>
  </div>
  <div class="sec-body" id="sec-ryze">
    <div class="row">
      <span class="lbl">Enable</span>
      <div class="inp" style="display:flex;align-items:center;gap:8px;">
        <label class="tog"><input type="checkbox" id="ryzeEnabled"><span class="trk"></span></label>
        <span class="tlbl" onclick="document.getElementById('ryzeEnabled').click()">Show background</span>
      </div>
    </div>
    <div class="row">
      <span class="lbl">Front text</span>
      <div class="inp"><input type="text" id="ryzeText" maxlength="20" placeholder="IUDEX"></div>
    </div>
    <div class="row">
      <span class="lbl">Back text</span>
      <div class="inp"><input type="text" id="ryzeBackText" maxlength="20" placeholder="RYZE"></div>
    </div>
    <div class="row">
      <span class="lbl">Opacity</span>
      <div class="inp sl-row">
        <input type="range" id="ryzeOpacity" min="5" max="100" step="5">
        <span class="sl-val" id="ryzeOpacityVal">100%</span>
      </div>
    </div>
    <div class="row">
      <span class="lbl">Speed</span>
      <div class="inp sl-row">
        <input type="range" id="ryzeSpeed" min="1" max="60" step="1">
        <span class="sl-val" id="ryzeSpeedVal">18s</span>
      </div>
    </div>
    <div class="row">
      <span class="lbl">Size</span>
      <div class="inp sl-row">
        <input type="range" id="ryzeSize" min="5" max="30" step="1">
        <span class="sl-val" id="ryzeSizeVal">14vw</span>
      </div>
    </div>
    <div class="row">
      <span class="lbl">Glow color</span>
      <div class="inp col-row">
        <input type="color" id="ryzeGlowColor">
        <input type="text" class="hex" id="ryzeGlowColorHex" maxlength="7">
      </div>
    </div>
    <div class="row">
      <span class="lbl">Extrude</span>
      <div class="inp col-row">
        <input type="color" id="ryzeExtrudeColor">
        <input type="text" class="hex" id="ryzeExtrudeColorHex" maxlength="7">
      </div>
    </div>
    <div class="row">
      <span class="lbl">Glow intens.</span>
      <div class="inp sl-row">
        <input type="range" id="ryzeGlowIntensity" min="0" max="50" step="1">
        <span class="sl-val" id="ryzeGlowIntensityVal">18%</span>
      </div>
    </div>
  </div>
</div>

<!-- Glitch -->
<div class="sec">
  <div class="sec-hdr" data-sec="glitch">
    <span class="sec-title">Glitch</span>
    <i class="chev o" id="ch-glitch">&#9658;</i>
  </div>
  <div class="sec-body" id="sec-glitch">
    <div class="row">
      <span class="lbl">Enable</span>
      <div class="inp" style="display:flex;align-items:center;gap:8px;">
        <label class="tog"><input type="checkbox" id="ryzeGlitchEnabled"><span class="trk"></span></label>
        <span class="tlbl" onclick="document.getElementById('ryzeGlitchEnabled').click()">Text &amp; BG glitch</span>
      </div>
    </div>
    <div class="row">
      <span class="lbl">Type glitch</span>
      <div class="inp" style="display:flex;align-items:center;gap:8px;">
        <label class="tog"><input type="checkbox" id="ryzeTypingGlitch"><span class="trk"></span></label>
        <span class="tlbl" onclick="document.getElementById('ryzeTypingGlitch').click()">Glitch on keypress</span>
      </div>
    </div>
    <div class="row">
      <span class="lbl">Intensity</span>
      <div class="inp sl-row">
        <input type="range" id="ryzeGlitchIntensity" min="0" max="100" step="5">
        <span class="sl-val" id="ryzeGlitchIntensityVal">70%</span>
      </div>
    </div>
    <div class="row">
      <span class="lbl">Frequency</span>
      <div class="inp sl-row">
        <input type="range" id="ryzeGlitchFrequency" min="2" max="30" step="1">
        <span class="sl-val" id="ryzeGlitchFrequencyVal">7s</span>
      </div>
    </div>
  </div>
</div>

<!-- Syntax Colors -->
<div class="sec">
  <div class="sec-hdr" data-sec="syntax">
    <span class="sec-title">Syntax Glow</span>
    <i class="chev o" id="ch-syntax">&#9658;</i>
  </div>
  <div class="sec-body" id="sec-syntax">
    <div class="row">
      <span class="lbl">Glow</span>
      <div class="inp" style="display:flex;align-items:center;gap:8px;">
        <label class="tog"><input type="checkbox" id="syntaxGlowEnabled"><span class="trk"></span></label>
        <span class="tlbl" onclick="document.getElementById('syntaxGlowEnabled').click()">Enable text glow</span>
      </div>
    </div>
    <div class="grid2">
      <div class="col-item">
        <span class="col-item-lbl">Strings</span>
        <div class="col-row"><input type="color" id="colorStrings"><input type="text" class="hex" id="colorStringsHex" maxlength="7"></div>
      </div>
      <div class="col-item">
        <span class="col-item-lbl">Types</span>
        <div class="col-row"><input type="color" id="colorTypes"><input type="text" class="hex" id="colorTypesHex" maxlength="7"></div>
      </div>
      <div class="col-item">
        <span class="col-item-lbl">Keywords</span>
        <div class="col-row"><input type="color" id="colorKeywords"><input type="text" class="hex" id="colorKeywordsHex" maxlength="7"></div>
      </div>
      <div class="col-item">
        <span class="col-item-lbl">Numbers</span>
        <div class="col-row"><input type="color" id="colorNumbers"><input type="text" class="hex" id="colorNumbersHex" maxlength="7"></div>
      </div>
      <div class="col-item">
        <span class="col-item-lbl">Functions</span>
        <div class="col-row"><input type="color" id="colorFunctions"><input type="text" class="hex" id="colorFunctionsHex" maxlength="7"></div>
      </div>
      <div class="col-item">
        <span class="col-item-lbl">Variables</span>
        <div class="col-row"><input type="color" id="colorVariables"><input type="text" class="hex" id="colorVariablesHex" maxlength="7"></div>
      </div>
      <div class="col-item">
        <span class="col-item-lbl">Errors</span>
        <div class="col-row"><input type="color" id="colorErrors"><input type="text" class="hex" id="colorErrorsHex" maxlength="7"></div>
      </div>
      <div class="col-item">
        <span class="col-item-lbl">Comments</span>
        <div class="col-row"><input type="color" id="colorComments"><input type="text" class="hex" id="colorCommentsHex" maxlength="7"></div>
      </div>
    </div>
  </div>
</div>

<!-- Cursor -->
<div class="sec">
  <div class="sec-hdr" data-sec="cursor">
    <span class="sec-title">Cursor</span>
    <i class="chev" id="ch-cursor">&#9658;</i>
  </div>
  <div class="sec-body clp" id="sec-cursor">
    <div class="row">
      <span class="lbl">Primary</span>
      <div class="inp col-row"><input type="color" id="cursorColor1"><input type="text" class="hex" id="cursorColor1Hex" maxlength="7"></div>
    </div>
    <div class="row">
      <span class="lbl">Secondary</span>
      <div class="inp col-row"><input type="color" id="cursorColor2"><input type="text" class="hex" id="cursorColor2Hex" maxlength="7"></div>
    </div>
    <div class="row">
      <span class="lbl">Pulse speed</span>
      <div class="inp sl-row">
        <input type="range" id="cursorPulseSpeed" min="5" max="30" step="1">
        <span class="sl-val" id="cursorPulseSpeedVal">1.4s</span>
      </div>
    </div>
  </div>
</div>

<!-- Effects -->
<div class="sec">
  <div class="sec-hdr" data-sec="effects">
    <span class="sec-title">Effects</span>
    <i class="chev" id="ch-effects">&#9658;</i>
  </div>
  <div class="sec-body clp" id="sec-effects">
    <div class="row">
      <span class="lbl">Scanlines</span>
      <div class="inp" style="display:flex;align-items:center;gap:8px;">
        <label class="tog"><input type="checkbox" id="scanlinesEnabled"><span class="trk"></span></label>
        <span class="tlbl" onclick="document.getElementById('scanlinesEnabled').click()">CRT scanlines</span>
      </div>
    </div>
    <div class="row">
      <span class="lbl">Opacity</span>
      <div class="inp sl-row">
        <input type="range" id="scanlinesOpacity" min="0" max="20" step="1">
        <span class="sl-val" id="scanlinesOpacityVal">6%</span>
      </div>
    </div>
    <div class="row">
      <span class="lbl">Scrollbar</span>
      <div class="inp col-row"><input type="color" id="scrollbarColor"><input type="text" class="hex" id="scrollbarColorHex" maxlength="7"></div>
    </div>
    <div class="row">
      <span class="lbl">Scroll hover</span>
      <div class="inp col-row"><input type="color" id="scrollbarHoverColor"><input type="text" class="hex" id="scrollbarHoverColorHex" maxlength="7"></div>
    </div>
  </div>
</div>

  </div><!-- /msec-body -->
</div><!-- /msec Background Console -->

<!-- QUICK COMMANDS -->
<div class="msec">
  <div class="msec-hdr">
    <div class="msec-hdr-left" id="masterHdr-qc">
      <i class="chev" id="ch-qc">&#9658;</i>
      <span class="msec-title">Quick Commands</span>
    </div>
  </div>
  <div class="msec-body clp" id="sec-qc">
    <div class="qc-list" id="qcList"></div>
    <div class="qc-add">
      <input type="text" id="qcLabel" placeholder="Label" style="flex:0 0 80px;">
      <input type="text" id="qcCmd"   placeholder="Command…">
      <button class="qc-add-btn" id="qcAddBtn">+</button>
    </div>
  </div>
</div>

<!-- FOCUS MODE -->
<div class="msec">
  <div class="msec-hdr">
    <div class="msec-hdr-left" id="masterHdr-focus">
      <i class="chev" id="ch-focus">&#9658;</i>
      <span class="msec-title">Focus Mode</span>
    </div>
  </div>
  <div class="msec-body clp" id="sec-focus">
    <div class="row"><span class="lbl">Activity Bar</span><div class="inp" style="display:flex;align-items:center;gap:8px;"><label class="tog"><input type="checkbox" id="focusActivityBar"><span class="trk"></span></label><span class="tlbl" onclick="document.getElementById('focusActivityBar').click()">Visible</span></div></div>
    <div class="row"><span class="lbl">Status Bar</span><div class="inp" style="display:flex;align-items:center;gap:8px;"><label class="tog"><input type="checkbox" id="focusStatusBar"><span class="trk"></span></label><span class="tlbl" onclick="document.getElementById('focusStatusBar').click()">Visible</span></div></div>
    <div class="row"><span class="lbl">Minimap</span><div class="inp" style="display:flex;align-items:center;gap:8px;"><label class="tog"><input type="checkbox" id="focusMinimap"><span class="trk"></span></label><span class="tlbl" onclick="document.getElementById('focusMinimap').click()">Visible</span></div></div>
    <div class="row"><span class="lbl">Breadcrumbs</span><div class="inp" style="display:flex;align-items:center;gap:8px;"><label class="tog"><input type="checkbox" id="focusBreadcrumbs"><span class="trk"></span></label><span class="tlbl" onclick="document.getElementById('focusBreadcrumbs').click()">Visible</span></div></div>
    <div class="row"><span class="lbl">Panel</span><div class="inp" style="display:flex;align-items:center;gap:8px;"><label class="tog"><input type="checkbox" id="focusPanel"><span class="trk"></span></label><span class="tlbl" onclick="document.getElementById('focusPanel').click()">Visible</span></div></div>
  </div>
</div>

<!-- FONT CONTROLS -->
<div class="msec">
  <div class="msec-hdr">
    <div class="msec-hdr-left" id="masterHdr-font">
      <i class="chev" id="ch-font">&#9658;</i>
      <span class="msec-title">Font Controls</span>
    </div>
  </div>
  <div class="msec-body clp" id="sec-font">
    <div class="row"><span class="lbl">Family</span><div class="inp"><input type="text" id="fontFamily" placeholder="Default"></div></div>
    <div class="row"><span class="lbl">Size</span><div class="inp sl-row"><input type="range" id="fontSize" min="10" max="28" step="1"><span class="sl-val" id="fontSizeVal">14px</span></div></div>
    <div class="row"><span class="lbl">Line height</span><div class="inp sl-row"><input type="range" id="lineHeight" min="0" max="60" step="1"><span class="sl-val" id="lineHeightVal">0</span></div></div>
    <div class="row"><span class="lbl">Letter spc.</span><div class="inp sl-row"><input type="range" id="letterSpacing" min="-2" max="10" step="0.5"><span class="sl-val" id="letterSpacingVal">0px</span></div></div>
    <button class="font-reset" id="fontResetBtn">Reset to VS Code defaults</button>
  </div>
</div>

<!-- SCRATCH PAD -->
<div class="msec">
  <div class="msec-hdr">
    <div class="msec-hdr-left" id="masterHdr-scratch">
      <i class="chev" id="ch-scratch">&#9658;</i>
      <span class="msec-title">Scratch Pad</span>
    </div>
  </div>
  <div class="msec-body clp" id="sec-scratch">
    <div class="scratch-wrap">
      <textarea class="scratch-area" id="scratchText" placeholder="Notes, snippets, temp values…" spellcheck="false"></textarea>
      <div class="scratch-meta" id="scratchMeta">auto-saved · per workspace</div>
    </div>
  </div>
</div>

<!-- COLOR TOOLS -->
<div class="msec">
  <div class="msec-hdr">
    <div class="msec-hdr-left" id="masterHdr-ct">
      <i class="chev" id="ch-ct">&#9658;</i>
      <span class="msec-title">Color Tools</span>
    </div>
  </div>
  <div class="msec-body clp" id="sec-ct">
    <div class="ct-picker-row">
      <span class="ct-picker-lbl">Pick</span>
      <input type="color" id="ctPicker" value="#00d4b1" style="width:36px;height:26px;flex-shrink:0;">
      <div class="ct-preview" id="ctPreview" style="flex:1;height:26px;background:#00d4b1;"></div>
    </div>
    <div class="ct-row"><span class="ct-fmt">HEX</span><span class="ct-val" id="ctHex">#00d4b1</span><button class="ct-copy" data-fmt="hex">Copy</button></div>
    <div class="ct-row"><span class="ct-fmt">RGB</span><span class="ct-val" id="ctRgb">rgb(0, 212, 177)</span><button class="ct-copy" data-fmt="rgb">Copy</button></div>
    <div class="ct-row"><span class="ct-fmt">HSL</span><span class="ct-val" id="ctHsl">hsl(171, 100%, 42%)</span><button class="ct-copy" data-fmt="hsl">Copy</button></div>
  </div>
</div>

<!-- PATH UTILS -->
<div class="msec">
  <div class="msec-hdr">
    <div class="msec-hdr-left" id="masterHdr-path">
      <i class="chev" id="ch-path">&#9658;</i>
      <span class="msec-title">Path Utils</span>
    </div>
  </div>
  <div class="msec-body clp" id="sec-path">
    <div class="pu-grid">
      <button class="pu-btn" id="puAbsolute">Copy Absolute</button>
      <button class="pu-btn" id="puRelative">Copy Relative</button>
      <button class="pu-btn" id="puFilename">Copy Filename</button>
      <button class="pu-btn" id="puDir">Copy Directory</button>
    </div>
    <div class="pu-info" id="puInfo">Open a file to copy its path.</div>
  </div>
</div>

<!-- TODO SCANNER -->
<div class="msec">
  <div class="msec-hdr">
    <div class="msec-hdr-left" id="masterHdr-todo">
      <i class="chev" id="ch-todo">&#9658;</i>
      <span class="msec-title">TODO Scanner</span>
    </div>
  </div>
  <div class="msec-body clp" id="sec-todo">
    <button class="todo-scan-btn" id="todoScanBtn">Scan Workspace</button>
    <div class="todo-list" id="todoList">
      <div class="todo-empty">Click scan to find TODOs, FIXMEs &amp; HACKs.</div>
    </div>
  </div>
</div>

<!-- GIT QUICK ACTIONS -->
<div class="msec">
  <div class="msec-hdr">
    <div class="msec-hdr-left" id="masterHdr-git">
      <i class="chev" id="ch-git">&#9658;</i>
      <span class="msec-title">Git Quick Actions</span>
    </div>
  </div>
  <div class="msec-body clp" id="sec-git">
    <div class="git-grid">
      <button class="git-btn" id="gitStatus">git status</button>
      <button class="git-btn" id="gitStageAll">git add -A</button>
      <button class="git-btn" id="gitPull">git pull</button>
      <button class="git-btn" id="gitPush">git push</button>
    </div>
    <div class="git-commit-row">
      <input type="text" id="gitMsg" placeholder="Commit message…">
      <button class="git-commit-btn" id="gitCommitBtn">Commit</button>
    </div>
  </div>
</div>

<!-- SNIPPET BANK -->
<div class="msec">
  <div class="msec-hdr">
    <div class="msec-hdr-left" id="masterHdr-snip">
      <i class="chev" id="ch-snip">&#9658;</i>
      <span class="msec-title">Snippet Bank</span>
    </div>
  </div>
  <div class="msec-body clp" id="sec-snip">
    <div class="snip-list" id="snipList"></div>
    <div class="snip-add-wrap">
      <input type="text" id="snipLabel" placeholder="Label…">
      <textarea class="snip-add-body" id="snipBody" placeholder="Snippet content…"></textarea>
      <div class="snip-add-footer">
        <button class="snip-add-btn" id="snipAddBtn">+ Save Snippet</button>
      </div>
    </div>
  </div>
</div>

<!-- TEXT TRANSFORM -->
<div class="msec">
  <div class="msec-hdr">
    <div class="msec-hdr-left" id="masterHdr-tt">
      <i class="chev" id="ch-tt">&#9658;</i>
      <span class="msec-title">Text Transform</span>
    </div>
  </div>
  <div class="msec-body clp" id="sec-tt">
    <textarea class="tt-area" id="ttInput" placeholder="Paste or type text here…"></textarea>
    <div class="tt-grid">
      <button class="tt-btn" data-fn="upper">UPPER CASE</button>
      <button class="tt-btn" data-fn="lower">lower case</button>
      <button class="tt-btn" data-fn="title">Title Case</button>
      <button class="tt-btn" data-fn="camel">camelCase</button>
      <button class="tt-btn" data-fn="snake">snake_case</button>
      <button class="tt-btn" data-fn="kebab">kebab-case</button>
      <button class="tt-btn" data-fn="screaming">SCREAMING_SNAKE</button>
      <button class="tt-btn" data-fn="trim">Trim Whitespace</button>
      <button class="tt-btn" data-fn="urlencode">URL Encode</button>
      <button class="tt-btn" data-fn="urldecode">URL Decode</button>
      <button class="tt-btn" data-fn="b64enc">Base64 Encode</button>
      <button class="tt-btn" data-fn="b64dec">Base64 Decode</button>
    </div>
    <div class="tt-out-lbl">Result</div>
    <textarea class="tt-area" id="ttOutput" placeholder="Result appears here…" readonly style="border-left-color:var(--mu);opacity:0.85;min-height:50px;"></textarea>
    <div class="tt-copy-row">
      <button class="tt-copy-btn" id="ttCopyBtn">Copy Result</button>
    </div>
  </div>
</div>

<!-- TIMESTAMP TOOLS -->
<div class="msec">
  <div class="msec-hdr">
    <div class="msec-hdr-left" id="masterHdr-ts">
      <i class="chev" id="ch-ts">&#9658;</i>
      <span class="msec-title">Timestamp Tools</span>
    </div>
  </div>
  <div class="msec-body clp" id="sec-ts">
    <div class="ts-now" id="tsNow">—</div>
    <div class="ts-conv-row">
      <input type="text" id="tsEpochIn" placeholder="Unix timestamp…">
      <button class="ts-conv-btn" id="tsEpochConv">&#8594; ISO</button>
    </div>
    <div class="ts-result" id="tsEpochOut"></div>
    <button class="ts-copy-btn" id="tsEpochCopy">Copy</button>
    <div class="ts-conv-row">
      <input type="text" id="tsIsoIn" placeholder="ISO date (2024-01-15T10:30:00Z)…">
      <button class="ts-conv-btn" id="tsIsoConv">&#8594; Epoch</button>
    </div>
    <div class="ts-result" id="tsIsoOut"></div>
    <button class="ts-copy-btn" id="tsIsoCopy">Copy</button>
  </div>
</div>

<!-- REGEX TESTER -->
<div class="msec">
  <div class="msec-hdr">
    <div class="msec-hdr-left" id="masterHdr-rx">
      <i class="chev" id="ch-rx">&#9658;</i>
      <span class="msec-title">Regex Tester</span>
    </div>
  </div>
  <div class="msec-body clp" id="sec-rx">
    <div class="rx-row">
      <span class="rx-lbl">Pattern + Flags</span>
      <div class="rx-pat-row">
        <input type="text" id="rxPattern" placeholder="pattern">
        <input type="text" id="rxFlags" class="rx-flags" placeholder="gi">
      </div>
    </div>
    <div class="rx-row">
      <span class="rx-lbl">Test String</span>
      <textarea class="rx-test" id="rxTest" placeholder="Test string…"></textarea>
    </div>
    <div class="rx-results" id="rxResults"><span class="rx-no-match">Enter a pattern and test string.</span></div>
    <div class="rx-count" id="rxCount"></div>
  </div>
</div>

<script>
var vscode = acquireVsCodeApi();
var settings = ${s};

var sliders = [
  { id: 'ryzeOpacity',         key: 'ryzeOpacity',         fmt: function(v){ return v + '%'; } },
  { id: 'ryzeSpeed',           key: 'ryzeSpeed',           fmt: function(v){ return v + 's'; } },
  { id: 'ryzeSize',            key: 'ryzeSize',            fmt: function(v){ return v + 'vw'; } },
  { id: 'ryzeGlowIntensity',   key: 'ryzeGlowIntensity',   fmt: function(v){ return v + '%'; } },
  { id: 'ryzeGlitchIntensity', key: 'ryzeGlitchIntensity', fmt: function(v){ return v + '%'; } },
  { id: 'ryzeGlitchFrequency', key: 'ryzeGlitchFrequency', fmt: function(v){ return v + 's'; } },
  { id: 'cursorPulseSpeed',    key: 'cursorPulseSpeed',    fmt: function(v){ return (v/10).toFixed(1) + 's'; } },
  { id: 'scanlinesOpacity',    key: 'scanlinesOpacity',    fmt: function(v){ return v + '%'; } },
];

var colors = [
  'ryzeGlowColor','ryzeExtrudeColor',
  'colorStrings','colorTypes','colorKeywords','colorNumbers',
  'colorFunctions','colorVariables','colorErrors','colorComments',
  'cursorColor1','cursorColor2','scrollbarColor','scrollbarHoverColor',
];

var toggles = ['ryzeEnabled','scanlinesEnabled','ryzeGlitchEnabled','ryzeTypingGlitch','syntaxGlowEnabled'];
var texts   = ['ryzeText','ryzeBackText'];

function cssColorToHex(color) {
  if (!color) return null;
  color = color.trim();
  if (/^#[0-9a-fA-F]{6}$/.test(color)) return color;
  if (/^#[0-9a-fA-F]{3}$/.test(color)) {
    return '#' + color[1]+color[1]+color[2]+color[2]+color[3]+color[3];
  }
  var m = color.match(/\d+/g);
  if (m && m.length >= 3) {
    return '#' + [m[0],m[1],m[2]].map(function(n){
      return parseInt(n).toString(16).padStart(2,'0');
    }).join('');
  }
  return null;
}

function themeVar(name) {
  return cssColorToHex(getComputedStyle(document.body).getPropertyValue(name));
}

function pickFromTheme() {
  var updates = {
    colorStrings:        themeVar('--vscode-terminal-ansiGreen')         || themeVar('--vscode-charts-green')               || settings.colorStrings,
    colorTypes:          themeVar('--vscode-terminal-ansiCyan')          || themeVar('--vscode-charts-blue')                || settings.colorTypes,
    colorKeywords:       themeVar('--vscode-terminal-ansiMagenta')       || themeVar('--vscode-charts-purple')              || settings.colorKeywords,
    colorNumbers:        themeVar('--vscode-terminal-ansiYellow')        || themeVar('--vscode-charts-yellow')              || settings.colorNumbers,
    colorFunctions:      themeVar('--vscode-terminal-ansiBrightYellow')  || themeVar('--vscode-charts-orange')              || settings.colorFunctions,
    colorVariables:      themeVar('--vscode-terminal-ansiBlue')          || themeVar('--vscode-charts-blue')                || settings.colorVariables,
    colorErrors:         themeVar('--vscode-terminal-ansiRed')           || themeVar('--vscode-charts-red')                 || settings.colorErrors,
    colorComments:       themeVar('--vscode-editorLineNumber-foreground')                                                    || settings.colorComments,
    cursorColor1:        themeVar('--vscode-editorCursor-foreground')    || themeVar('--vscode-focusBorder')                || settings.cursorColor1,
    cursorColor2:        themeVar('--vscode-focusBorder')                || themeVar('--vscode-activityBarBadge-background') || settings.cursorColor2,
    ryzeGlowColor:       themeVar('--vscode-focusBorder')                || themeVar('--vscode-activityBarBadge-background') || settings.ryzeGlowColor,
    ryzeExtrudeColor:    themeVar('--vscode-editorLink-activeForeground')|| themeVar('--vscode-terminal-ansiMagenta')       || settings.ryzeExtrudeColor,
    scrollbarColor:      themeVar('--vscode-scrollbarSlider-background')                                                    || settings.scrollbarColor,
    scrollbarHoverColor: themeVar('--vscode-scrollbarSlider-hoverBackground')                                               || settings.scrollbarHoverColor,
  };
  Object.assign(settings, updates);
  refreshControls();
  save();
  vscode.postMessage({ type: 'apply', settings: settings });
  showStatus('THEME COLORS APPLIED');
}

function showStatus(msg) {
  var bar = document.getElementById('stBar');
  var txt = document.getElementById('stTxt');
  txt.textContent = msg || 'CSS WRITTEN — RELOAD TO APPLY';
  bar.classList.add('on');
  setTimeout(function(){ bar.classList.remove('on'); txt.textContent = 'STANDBY'; }, 3000);
}

function refreshControls() {
  sliders.forEach(function(sl) {
    var el  = document.getElementById(sl.id);
    var val = document.getElementById(sl.id + 'Val');
    el.value = settings[sl.key];
    val.textContent = sl.fmt(settings[sl.key]);
  });
  colors.forEach(function(key) {
    document.getElementById(key).value = settings[key];
    document.getElementById(key + 'Hex').value = settings[key];
  });
  toggles.forEach(function(key) {
    document.getElementById(key).checked = settings[key];
  });
  texts.forEach(function(key) {
    document.getElementById(key).value = settings[key];
  });
}

function init() {
  refreshControls();

  sliders.forEach(function(sl) {
    var el  = document.getElementById(sl.id);
    var val = document.getElementById(sl.id + 'Val');
    el.addEventListener('input', function(e) {
      settings[sl.key] = parseFloat(e.target.value);
      val.textContent = sl.fmt(settings[sl.key]);
      save();
    });
  });

  colors.forEach(function(key) {
    var picker = document.getElementById(key);
    var hex    = document.getElementById(key + 'Hex');
    picker.addEventListener('input', function(e) {
      settings[key] = e.target.value;
      hex.value = e.target.value;
      save();
    });
    hex.addEventListener('input', function(e) {
      if (/^#[0-9a-fA-F]{6}$/.test(e.target.value)) {
        settings[key] = e.target.value;
        picker.value = e.target.value;
        save();
      }
    });
  });

  toggles.forEach(function(key) {
    document.getElementById(key).addEventListener('change', function(e) {
      settings[key] = e.target.checked;
      save();
    });
  });

  texts.forEach(function(key) {
    document.getElementById(key).addEventListener('input', function(e) {
      settings[key] = e.target.value;
      save();
    });
  });

  document.querySelectorAll('.sec-hdr').forEach(function(hdr) {
    hdr.addEventListener('click', function() {
      var sec = hdr.getAttribute('data-sec');
      document.getElementById('sec-' + sec).classList.toggle('clp');
      document.getElementById('ch-' + sec).classList.toggle('o');
    });
  });

  document.getElementById('masterHdr').addEventListener('click', function() {
    document.getElementById('sec-master').classList.toggle('clp');
    document.getElementById('ch-master').classList.toggle('o');
  });
  document.getElementById('masterEnabled').addEventListener('change', function(e) {
    vscode.postMessage({ type: 'master-toggle', value: e.target.checked });
  });

  document.getElementById('btnApply').addEventListener('click', function() {
    vscode.postMessage({ type: 'apply', settings: settings });
    showStatus('CSS WRITTEN — RELOAD TO APPLY');
  });
  document.getElementById('btnReload').addEventListener('click', function() {
    vscode.postMessage({ type: 'reload' });
  });
  document.getElementById('btnReset').addEventListener('click', function() {
    vscode.postMessage({ type: 'reset' });
  });
  document.getElementById('btnTheme').addEventListener('click', pickFromTheme);
}

function save() {
  vscode.postMessage({ type: 'save', settings: settings });
}

window.addEventListener('message', function(e) {
  if (e.data.type === 'settings')      { settings = e.data.settings; refreshControls(); }
  if (e.data.type === 'font-loaded')   { applyFontSettings(e.data.font); }
  if (e.data.type === 'focus-loaded')  { applyFocusState(e.data.focus); }
  if (e.data.type === 'todo-results')  { renderTodos(e.data.results); }
});

/* ─── collapse helpers for all outer sections ─── */
['qc','focus','font','scratch','ct','path','todo','git','snip','tt','ts','rx'].forEach(function(key) {
  var hdr = document.getElementById('masterHdr-' + key);
  if (!hdr) return;
  hdr.addEventListener('click', function() {
    var body = document.getElementById('sec-' + key);
    var chev = document.getElementById('ch-' + key);
    if (body) body.classList.toggle('clp');
    if (chev) chev.classList.toggle('o');
  });
});

/* ─── core init — must run before any section JS that might throw ─── */
init();

/* ─── QUICK COMMANDS ─── */
var quickCommands = ${JSON.stringify(extra.quickCommands)};

function renderQC() {
  var list = document.getElementById('qcList');
  if (!quickCommands.length) {
    list.innerHTML = '<div class="qc-empty">No commands yet</div>';
    return;
  }
  list.innerHTML = quickCommands.map(function(c, i) {
    return '<div class="qc-item">' +
      '<span class="qc-lbl" title="' + c.cmd.replace(/"/g,'&quot;') + '">' + c.label + '</span>' +
      '<button class="qc-run" data-i="' + i + '">Run</button>' +
      '<button class="qc-del" data-i="' + i + '">✕</button>' +
    '</div>';
  }).join('');
  list.querySelectorAll('.qc-run').forEach(function(btn) {
    btn.addEventListener('click', function() {
      vscode.postMessage({ type: 'run-command', cmd: quickCommands[+btn.dataset.i].cmd });
    });
  });
  list.querySelectorAll('.qc-del').forEach(function(btn) {
    btn.addEventListener('click', function() {
      quickCommands.splice(+btn.dataset.i, 1);
      vscode.postMessage({ type: 'save-commands', commands: quickCommands });
      renderQC();
    });
  });
}
renderQC();

document.getElementById('qcAddBtn').addEventListener('click', function() {
  var lbl = document.getElementById('qcLabel').value.trim();
  var cmd = document.getElementById('qcCmd').value.trim();
  if (!cmd) return;
  quickCommands.push({ label: lbl || cmd, cmd: cmd });
  vscode.postMessage({ type: 'save-commands', commands: quickCommands });
  document.getElementById('qcLabel').value = '';
  document.getElementById('qcCmd').value = '';
  renderQC();
});
document.getElementById('qcCmd').addEventListener('keydown', function(e) {
  if (e.key === 'Enter') document.getElementById('qcAddBtn').click();
});

/* ─── FOCUS MODE ─── */
var focusState = ${JSON.stringify(extra.focusState)};
var focusMap = {
  focusActivityBar: 'activityBar',
  focusStatusBar:   'statusBar',
  focusMinimap:     'minimap',
  focusBreadcrumbs: 'breadcrumbs',
  focusPanel:       'panel',
};
function applyFocusState(state) {
  focusState = state;
  Object.keys(focusMap).forEach(function(id) {
    var el = document.getElementById(id);
    if (el) el.checked = !!state[focusMap[id]];
  });
}
applyFocusState(focusState);
Object.keys(focusMap).forEach(function(id) {
  document.getElementById(id).addEventListener('change', function(e) {
    var key = focusMap[id];
    focusState[key] = e.target.checked;
    vscode.postMessage({ type: 'focus-toggle', key: key, value: e.target.checked });
  });
});

/* ─── FONT CONTROLS ─── */
var fontSettings = ${JSON.stringify(extra.fontSettings)};
function applyFontSettings(f) {
  fontSettings = f;
  document.getElementById('fontFamily').value    = f.fontFamily    || '';
  document.getElementById('fontSize').value      = f.fontSize      || 14;
  document.getElementById('fontSizeVal').textContent = (f.fontSize || 14) + 'px';
  document.getElementById('lineHeight').value    = f.lineHeight    || 0;
  document.getElementById('lineHeightVal').textContent = f.lineHeight || 0;
  document.getElementById('letterSpacing').value = f.letterSpacing || 0;
  document.getElementById('letterSpacingVal').textContent = (f.letterSpacing || 0) + 'px';
}
applyFontSettings(fontSettings);

document.getElementById('fontFamily').addEventListener('change', function(e) {
  vscode.postMessage({ type: 'font-update', section: 'editor', key: 'fontFamily', value: e.target.value || undefined });
});
document.getElementById('fontSize').addEventListener('input', function(e) {
  var v = +e.target.value;
  document.getElementById('fontSizeVal').textContent = v + 'px';
  vscode.postMessage({ type: 'font-update', section: 'editor', key: 'fontSize', value: v });
});
document.getElementById('lineHeight').addEventListener('input', function(e) {
  var v = +e.target.value;
  document.getElementById('lineHeightVal').textContent = v;
  vscode.postMessage({ type: 'font-update', section: 'editor', key: 'lineHeight', value: v });
});
document.getElementById('letterSpacing').addEventListener('input', function(e) {
  var v = +e.target.value;
  document.getElementById('letterSpacingVal').textContent = v + 'px';
  vscode.postMessage({ type: 'font-update', section: 'editor', key: 'letterSpacing', value: v });
});
document.getElementById('fontResetBtn').addEventListener('click', function() {
  vscode.postMessage({ type: 'font-reset' });
  setTimeout(function() {
    vscode.postMessage({ type: 'request-font' });
  }, 300);
});

/* ─── SCRATCH PAD ─── */
var scratchEl = document.getElementById('scratchText');
scratchEl.value = ${JSON.stringify(extra.scratchText)};
var scratchTimer;
scratchEl.addEventListener('input', function() {
  clearTimeout(scratchTimer);
  scratchTimer = setTimeout(function() {
    vscode.postMessage({ type: 'save-scratch', text: scratchEl.value });
    document.getElementById('scratchMeta').textContent = 'saved · per workspace';
  }, 500);
});

/* ─── COLOR TOOLS ─── */
function hexToRgbStr(hex) {
  var r = parseInt(hex.slice(1,3),16), g = parseInt(hex.slice(3,5),16), b = parseInt(hex.slice(5,7),16);
  return 'rgb(' + r + ', ' + g + ', ' + b + ')';
}
function hexToHsl(hex) {
  var r = parseInt(hex.slice(1,3),16)/255, g = parseInt(hex.slice(3,5),16)/255, b = parseInt(hex.slice(5,7),16)/255;
  var max = Math.max(r,g,b), min = Math.min(r,g,b), h, s, l = (max+min)/2;
  if (max === min) { h = s = 0; } else {
    var d = max - min;
    s = l > 0.5 ? d/(2-max-min) : d/(max+min);
    switch(max) {
      case r: h = ((g-b)/d + (g<b?6:0))/6; break;
      case g: h = ((b-r)/d + 2)/6; break;
      default: h = ((r-g)/d + 4)/6;
    }
  }
  return 'hsl(' + Math.round(h*360) + ', ' + Math.round(s*100) + '%, ' + Math.round(l*100) + '%)';
}
function updateColor(hex) {
  document.getElementById('ctPreview').style.background = hex;
  document.getElementById('ctHex').textContent = hex;
  document.getElementById('ctRgb').textContent = hexToRgbStr(hex);
  document.getElementById('ctHsl').textContent = hexToHsl(hex);
}
document.getElementById('ctPicker').addEventListener('input', function(e) { updateColor(e.target.value); });
document.querySelectorAll('.ct-copy').forEach(function(btn) {
  btn.addEventListener('click', function() {
    var fmt = btn.dataset.fmt;
    var text = fmt === 'hex' ? document.getElementById('ctHex').textContent
             : fmt === 'rgb' ? document.getElementById('ctRgb').textContent
             :                 document.getElementById('ctHsl').textContent;
    vscode.postMessage({ type: 'copy-color', text: text });
    btn.classList.add('flash');
    setTimeout(function() { btn.classList.remove('flash'); }, 600);
  });
});
updateColor('#00d4b1');

/* ─── PATH UTILS ─── */
try { (function() {
  var kindMap = { puAbsolute: 'absolute', puRelative: 'relative', puFilename: 'filename', puDir: 'dir' };
  Object.keys(kindMap).forEach(function(id) {
    var el = document.getElementById(id);
    if (!el) return;
    el.addEventListener('click', function() {
      vscode.postMessage({ type: 'copy-path', kind: kindMap[id] });
    });
  });
})(); } catch(e) {}

/* ─── TODO SCANNER ─── */
try { document.getElementById('todoScanBtn').addEventListener('click', function() {
  document.getElementById('todoList').innerHTML = '<div class="todo-empty">Scanning…</div>';
  vscode.postMessage({ type: 'scan-todos' });
}); } catch(e) {}

function renderTodos(results) {
  var list = document.getElementById('todoList');
  if (!results || !results.length) {
    list.innerHTML = '<div class="todo-empty">No TODOs found — clean codebase!</div>';
    return;
  }
  list.innerHTML = results.map(function(r) {
    return '<div class="todo-item"><div class="todo-item-hdr">' +
      '<span class="todo-tag ' + r.type + '">' + r.type + '</span>' +
      '<span class="todo-loc">' + r.file + ':' + r.line + '</span>' +
      '</div><div class="todo-txt">' + r.text.replace(/</g,'&lt;').replace(/>/g,'&gt;') + '</div></div>';
  }).join('');
}

/* ─── GIT QUICK ACTIONS ─── */
try { [['gitStatus','git status'],['gitStageAll','git add -A'],['gitPull','git pull'],['gitPush','git push']].forEach(function(pair) {
  document.getElementById(pair[0]).addEventListener('click', function() {
    vscode.postMessage({ type: 'run-command', cmd: pair[1] });
  });
});
document.getElementById('gitCommitBtn').addEventListener('click', function() {
  var msg = document.getElementById('gitMsg').value.trim();
  if (!msg) return;
  vscode.postMessage({ type: 'run-command', cmd: 'git commit -m ' + JSON.stringify(msg) });
  document.getElementById('gitMsg').value = '';
});
document.getElementById('gitMsg').addEventListener('keydown', function(e) {
  if (e.key === 'Enter') document.getElementById('gitCommitBtn').click();
}); } catch(e) {}

/* ─── SNIPPET BANK ─── */
var snippets = ${JSON.stringify(extra.snippets)};

function renderSnippets() {
  try {
    var list = document.getElementById('snipList');
    if (!list) return;
    if (!snippets.length) {
      list.innerHTML = '<div class="snip-empty">No snippets yet — save one below.</div>';
      return;
    }
    list.innerHTML = snippets.map(function(s, i) {
      return '<div class="snip-item">' +
        '<span class="snip-lbl" title="' + s.text.replace(/"/g,'&quot;').slice(0,200) + '">' + s.label + '</span>' +
        '<button class="snip-ins" data-i="' + i + '">Insert</button>' +
        '<button class="snip-del" data-i="' + i + '">&#x2715;</button>' +
      '</div>';
    }).join('');
    list.querySelectorAll('.snip-ins').forEach(function(btn) {
      btn.addEventListener('click', function() {
        vscode.postMessage({ type: 'insert-snippet', text: snippets[+btn.dataset.i].text });
      });
    });
    list.querySelectorAll('.snip-del').forEach(function(btn) {
      btn.addEventListener('click', function() {
        snippets.splice(+btn.dataset.i, 1);
        vscode.postMessage({ type: 'save-snippets', snippets: snippets });
        renderSnippets();
      });
    });
  } catch(e) {}
}
try { renderSnippets(); } catch(e) {}

try { document.getElementById('snipAddBtn').addEventListener('click', function() {
  var lbl = document.getElementById('snipLabel').value.trim();
  var txt = document.getElementById('snipBody').value;
  if (!txt.trim()) return;
  snippets.push({ label: lbl || txt.slice(0, 32).trim() + '…', text: txt });
  vscode.postMessage({ type: 'save-snippets', snippets: snippets });
  document.getElementById('snipLabel').value = '';
  document.getElementById('snipBody').value = '';
  renderSnippets();
}); } catch(e) {}

/* ─── TEXT TRANSFORM ─── */
try { (function() {
  function toTitleCase(s) { return s.replace(/\w\S*/g, function(t){ return t.charAt(0).toUpperCase()+t.slice(1).toLowerCase(); }); }
  function toCamel(s) { return s.trim().replace(/[\s\-_]+(.)/g,function(_,c){ return c.toUpperCase(); }).replace(/^./,function(c){ return c.toLowerCase(); }); }
  function toSnake(s) { return s.trim().replace(/[\s\-]+/g,'_').replace(/([a-z])([A-Z])/g,'$1_$2').toLowerCase(); }
  function toKebab(s) { return s.trim().replace(/[\s_]+/g,'-').replace(/([a-z])([A-Z])/g,'$1-$2').toLowerCase(); }

  document.querySelectorAll('.tt-btn').forEach(function(btn) {
    btn.addEventListener('click', function() {
      var inp = document.getElementById('ttInput').value;
      var out;
      switch(btn.dataset.fn) {
        case 'upper':     out = inp.toUpperCase(); break;
        case 'lower':     out = inp.toLowerCase(); break;
        case 'title':     out = toTitleCase(inp); break;
        case 'camel':     out = toCamel(inp); break;
        case 'snake':     out = toSnake(inp); break;
        case 'kebab':     out = toKebab(inp); break;
        case 'screaming': out = toSnake(inp).toUpperCase(); break;
        case 'trim':      out = inp.trim().replace(/[ \t]+/g,' '); break;
        case 'urlencode': out = encodeURIComponent(inp); break;
        case 'urldecode': try { out = decodeURIComponent(inp); } catch(e) { out = 'Invalid encoded string'; } break;
        case 'b64enc':    try { out = btoa(unescape(encodeURIComponent(inp))); } catch(e) { out = 'Encode error'; } break;
        case 'b64dec':    try { out = decodeURIComponent(escape(atob(inp))); } catch(e) { out = 'Invalid Base64'; } break;
        default:          out = inp;
      }
      document.getElementById('ttOutput').value = out;
    });
  });

  document.getElementById('ttCopyBtn').addEventListener('click', function() {
    var text = document.getElementById('ttOutput').value;
    if (text) vscode.postMessage({ type: 'copy-color', text: text });
  });
})(); } catch(e) {}

/* ─── TIMESTAMP TOOLS ─── */
try { (function() {
  function updateNow() {
    var now = Date.now();
    document.getElementById('tsNow').textContent =
      'Epoch: ' + Math.floor(now/1000) + '\n' + new Date().toISOString();
  }
  updateNow();
  setInterval(updateNow, 1000);

  document.getElementById('tsEpochConv').addEventListener('click', function() {
    var v = document.getElementById('tsEpochIn').value.trim();
    if (!v) return;
    var ms = v.length <= 10 ? +v * 1000 : +v;
    var d = new Date(ms);
    document.getElementById('tsEpochOut').textContent = isNaN(d.getTime()) ? 'Invalid timestamp' : d.toISOString() + '\n' + d.toLocaleString();
  });

  document.getElementById('tsIsoConv').addEventListener('click', function() {
    var v = document.getElementById('tsIsoIn').value.trim();
    if (!v) return;
    var d = new Date(v);
    document.getElementById('tsIsoOut').textContent = isNaN(d.getTime()) ? 'Invalid date string' : Math.floor(d.getTime()/1000) + ' (s)\n' + d.getTime() + ' (ms)';
  });

  document.getElementById('tsEpochCopy').addEventListener('click', function() {
    var t = document.getElementById('tsEpochOut').textContent;
    if (t) vscode.postMessage({ type: 'copy-color', text: t });
  });
  document.getElementById('tsIsoCopy').addEventListener('click', function() {
    var t = document.getElementById('tsIsoOut').textContent;
    if (t) vscode.postMessage({ type: 'copy-color', text: t });
  });
})(); } catch(e) {}

/* ─── REGEX TESTER ─── */
try { (function() {
  function runRegex() {
    var rawPat = document.getElementById('rxPattern').value;
    var flags  = document.getElementById('rxFlags').value.trim() || 'g';
    var test   = document.getElementById('rxTest').value;
    var results = document.getElementById('rxResults');
    var count   = document.getElementById('rxCount');
    if (!rawPat || !test) {
      results.innerHTML = '<span class="rx-no-match">Enter a pattern and test string.</span>';
      count.textContent = '';
      return;
    }
    try {
      var pat = rawPat.replace(/^\/(.*)\/[gimsuy]*$/, '$1');
      var gFlags = flags.includes('g') ? flags : flags + 'g';
      var re = new RegExp(pat, gFlags);
      var matches = test.match(re);
      if (!matches) {
        results.innerHTML = '<span class="rx-no-match">No matches.</span>';
        count.textContent = '';
      } else {
        results.innerHTML = matches.map(function(m) {
          return '<span class="rx-match">' + m.replace(/</g,'&lt;').replace(/>/g,'&gt;') + '</span>';
        }).join(' ');
        count.textContent = matches.length + ' match' + (matches.length !== 1 ? 'es' : '');
      }
    } catch(e) {
      results.innerHTML = '<span class="rx-error">' + e.message + '</span>';
      count.textContent = '';
    }
  }

  document.getElementById('rxPattern').addEventListener('input', runRegex);
  document.getElementById('rxFlags').addEventListener('input', runRegex);
  document.getElementById('rxTest').addEventListener('input', runRegex);
})(); } catch(e) {}
</script>
</body>
</html>`;
}

class ArchitectusProvider {
  constructor(context) {
    this._ctx = context;
    this._view = null;
  }

  resolveWebviewView(webviewView) {
    this._view = webviewView;
    webviewView.webview.options = { enableScripts: true };
    const settings = this._load();
    const extra = this._loadExtra();
    webviewView.webview.html = getWebviewHTML(settings, extra);

    webviewView.webview.onDidReceiveMessage(msg => {
      switch (msg.type) {
        case 'save':           this._save(msg.settings); break;
        case 'apply':          this._apply(msg.settings); break;
        case 'reload':         this._reload(); break;
        case 'reset':          this._reset(); break;
        case 'master-toggle':  this._masterToggle(msg.value); break;
        case 'run-command':    this._runCommand(msg.cmd); break;
        case 'save-commands':  this._ctx.globalState.update('architectusQuickCommands', msg.commands); break;
        case 'save-scratch':   this._ctx.workspaceState.update('architectusScratch', msg.text); break;
        case 'font-update':    this._updateFont(msg.section, msg.key, msg.value); break;
        case 'font-reset':     this._resetFonts(); break;
        case 'request-font':   this._sendFontSettings(); break;
        case 'focus-toggle':   this._focusToggle(msg.key, msg.value); break;
        case 'copy-color':     vscode.env.clipboard.writeText(msg.text); break;
        case 'copy-path':      this._copyPath(msg.kind); break;
        case 'scan-todos':     this._scanTodos(); break;
        case 'save-snippets':  this._ctx.globalState.update('architectusSnippets', msg.snippets); break;
        case 'insert-snippet': this._insertSnippet(msg.text); break;
      }
    });
  }

  _loadExtra() {
    const cfg = vscode.workspace.getConfiguration;
    return {
      quickCommands: this._ctx.globalState.get('architectusQuickCommands', [
        { label: 'Install deps', cmd: 'npm install' },
        { label: 'Dev server',   cmd: 'npm run dev'  },
        { label: 'Git status',   cmd: 'git status'   },
      ]),
      scratchText: this._ctx.workspaceState.get('architectusScratch', ''),
      snippets: this._ctx.globalState.get('architectusSnippets', []),
      fontSettings: {
        fontFamily:    cfg('editor').get('fontFamily',    ''),
        fontSize:      cfg('editor').get('fontSize',      14),
        lineHeight:    cfg('editor').get('lineHeight',    0),
        letterSpacing: cfg('editor').get('letterSpacing', 0),
      },
      focusState: {
        activityBar: cfg('workbench').get('activityBar.visible', true),
        statusBar:   cfg('workbench').get('statusBar.visible',   true),
        minimap:     cfg('editor').get('minimap.enabled',        true),
        breadcrumbs: cfg('breadcrumbs').get('enabled',           true),
        panel:       this._ctx.globalState.get('architectusPanelVisible', true),
      },
    };
  }

  _load() {
    const stored = this._ctx.globalState.get('architectusSettings', {});
    return Object.assign({}, DEFAULTS, stored);
  }

  _save(settings) {
    this._ctx.globalState.update('architectusSettings', settings);
  }

  _apply(settings) {
    this._save(settings);
    try {
      fs.writeFileSync(CSS_FILE, generateCSS(settings), 'utf8');
    } catch(e) {
      vscode.window.showErrorMessage('Architectus: Could not write CSS — ' + e.message);
      return;
    }
    vscode.window.showInformationMessage('Architectus: CSS written.');
  }

  _masterToggle(enable) {
    const s = this._load();
    s.masterEnabled = enable;
    this._save(s);
    if (enable) {
      this._apply(s);
    } else {
      try {
        fs.writeFileSync(CSS_FILE, '/* Architectus disabled */\n', 'utf8');
      } catch(e) {
        vscode.window.showErrorMessage('Architectus: Could not write CSS — ' + e.message);
        return;
      }
      vscode.window.showInformationMessage('Architectus: CSS disabled.');
    }
  }

  _runCommand(cmd) {
    const terminal = vscode.window.activeTerminal || vscode.window.createTerminal('Architectus');
    terminal.show(true);
    terminal.sendText(cmd);
  }

  _updateFont(section, key, value) {
    vscode.workspace.getConfiguration(section).update(key, value === '' ? undefined : value, vscode.ConfigurationTarget.Global);
  }

  _resetFonts() {
    const cfg = vscode.workspace.getConfiguration('editor');
    ['fontFamily','fontSize','lineHeight','letterSpacing'].forEach(k => cfg.update(k, undefined, vscode.ConfigurationTarget.Global));
  }

  _sendFontSettings() {
    if (!this._view) return;
    const cfg = vscode.workspace.getConfiguration;
    this._view.webview.postMessage({ type: 'font-loaded', font: {
      fontFamily:    cfg('editor').get('fontFamily',    ''),
      fontSize:      cfg('editor').get('fontSize',      14),
      lineHeight:    cfg('editor').get('lineHeight',    0),
      letterSpacing: cfg('editor').get('letterSpacing', 0),
    }});
  }

  _focusToggle(key, value) {
    const map = {
      activityBar: ['workbench',   'activityBar.visible'],
      statusBar:   ['workbench',   'statusBar.visible'],
      minimap:     ['editor',      'minimap.enabled'],
      breadcrumbs: ['breadcrumbs', 'enabled'],
    };
    if (key === 'panel') {
      this._ctx.globalState.update('architectusPanelVisible', value);
      vscode.commands.executeCommand(value ? 'workbench.action.openPanel' : 'workbench.action.closePanel');
    } else if (map[key]) {
      const [section, cfgKey] = map[key];
      vscode.workspace.getConfiguration(section).update(cfgKey, value, vscode.ConfigurationTarget.Global);
    }
  }

  _copyPath(kind) {
    const editor = vscode.window.activeTextEditor;
    if (!editor) { vscode.window.showWarningMessage('Architectus: No active file.'); return; }
    const absPath = editor.document.uri.fsPath;
    const workFolders = vscode.workspace.workspaceFolders;
    const root = workFolders && workFolders[0] ? workFolders[0].uri.fsPath : '';
    let text;
    if (kind === 'absolute')  text = absPath;
    else if (kind === 'relative') text = root ? path.relative(root, absPath) : absPath;
    else if (kind === 'filename') text = path.basename(absPath);
    else if (kind === 'dir')      text = path.dirname(absPath);
    vscode.env.clipboard.writeText(text);
    vscode.window.showInformationMessage('Architectus: Copied — ' + text);
  }

  async _scanTodos() {
    if (!this._view) return;
    const results = [];
    try {
      const files = await vscode.workspace.findFiles(
        '{**/*.js,**/*.ts,**/*.jsx,**/*.tsx,**/*.py,**/*.go,**/*.java,**/*.cs,**/*.cpp,**/*.c,**/*.md,**/*.rs,**/*.rb,**/*.php,**/*.swift}',
        '{**/node_modules/**,**/.git/**,**/dist/**,**/build/**,**/.next/**,**/out/**}',
        500
      );
      const regex = /\b(TODO|FIXME|HACK|XXX|NOTE)\b[:\s]*(.*)/i;
      const workRoot = vscode.workspace.workspaceFolders && vscode.workspace.workspaceFolders[0]
        ? vscode.workspace.workspaceFolders[0].uri.fsPath : '';
      for (const file of files.slice(0, 300)) {
        let content;
        try { content = fs.readFileSync(file.fsPath, 'utf8'); } catch(e) { continue; }
        content.split('\n').forEach((line, i) => {
          const m = line.match(regex);
          if (m) results.push({
            file: workRoot ? path.relative(workRoot, file.fsPath) : path.basename(file.fsPath),
            line: i + 1,
            type: m[1].toUpperCase(),
            text: m[2].trim().slice(0, 120),
          });
        });
      }
    } catch(e) {}
    this._view.webview.postMessage({ type: 'todo-results', results: results.slice(0, 300) });
  }

  _insertSnippet(text) {
    const editor = vscode.window.activeTextEditor;
    if (!editor) { vscode.window.showWarningMessage('Architectus: No active editor.'); return; }
    editor.edit(editBuilder => {
      const sel = editor.selection;
      if (sel.isEmpty) editBuilder.insert(sel.active, text);
      else editBuilder.replace(sel, text);
    });
  }

  _reload() {
    vscode.commands.executeCommand('workbench.action.reloadWindow');
  }

  _reset() {
    this._ctx.globalState.update('architectusSettings', DEFAULTS);
    if (this._view) {
      this._view.webview.postMessage({ type: 'settings', settings: DEFAULTS });
    }
  }
}

function activate(context) {
  const provider = new ArchitectusProvider(context);
  context.subscriptions.push(
    vscode.window.registerWebviewViewProvider('architectus.panel', provider)
  );
}

function deactivate() {}

module.exports = { activate, deactivate };
